import { HEAVENLY_STEMS, HEAVENLY_STEMS_EN, EARTHLY_BRANCHES, EARTHLY_BRANCHES_EN, STEM_WUXING, BRANCH_WUXING, CHINESE_ZODIAC_SIGNS } from "./constants";

export interface BirthYearInfo {
  year: number;
  stem: string;
  stemEn: string;
  branch: string;
  branchEn: string;
  stemBranch: string; // e.g. "甲子"
  stemBranchEn: string; // e.g. "Jia Zi"
  animal: string;
  animalKey: string;
  element: string;
  yinYang: "Yang" | "Yin";
  content: YearContent;
}

export interface YearContent {
  summary: string;
  personality: string[];
  career: string;
  love: string;
  health: string;
  luckyColors: string[];
  luckyNumbers: number[];
  compatibleAnimals: string[];
  incompatibleAnimals: string[];
  famous: string[];
}

/** 60 unique stem-branch combination contents keyed by stemBranch (Chinese) */
const YEAR_CONTENT: Record<string, Omit<YearContent, "famous">> = {
  "甲子": {
    summary: "Jia Zi combines Yang Wood (the towering tree) with the Rat's water element. This is a year of ambitious beginnings and hidden potential — like a seed planted in fertile winter soil, waiting to sprout.",
    personality: ["Ambitious and visionary with a practical streak", "Quick-witted and adaptable, able to navigate complex situations", "Independent but values close relationships", "Natural problem-solver with strong intuition"],
    career: "Jia Zi people excel in careers that combine big-picture thinking with practical execution. They thrive as entrepreneurs, architects, engineers, and strategic consultants. Their ability to see opportunities where others see obstacles makes them excellent innovators.",
    love: "In relationships, Jia Zi individuals are loyal and protective partners. They seek intellectual stimulation and emotional security. They are drawn to partners who appreciate their ambition while providing a stable home base.",
    health: "Focus on kidney and urinary system health (Water element). The Wood energy needs proper rest to avoid burnout. Regular moderate exercise like swimming or walking helps maintain balance.",
    luckyColors: ["Green", "Blue", "Black"],
    luckyNumbers: [1, 3, 6],
    compatibleAnimals: ["Ox", "Dragon", "Monkey"],
    incompatibleAnimals: ["Horse"],
  },
  "乙丑": {
    summary: "Yi Chou combines Yin Wood (the flowering vine) with the Ox's stable Earth. This is a year of patient, persistent growth — like a vine slowly covering a solid wall. Determination and reliability define this combination.",
    personality: ["Patient and persistent with a gentle approach", "Detail-oriented and methodical in all endeavors", "Strong sense of responsibility and loyalty", "Creative problem-solver who works well within structure"],
    career: "乙丑 people shine in roles that require patience and precision. They excel in education, research, agriculture, design, and craftsmanship. Their methodical nature makes them excellent project managers and quality assurance specialists.",
    love: "乙丑 individuals are devoted and attentive partners. They may be slow to open up, but once committed, they are unwavering in their loyalty. They value stability and create nurturing home environments.",
    health: "Pay attention to digestive health and the spleen/stomach system (Earth branch). Regular meal times and a balanced diet are essential. Gentle exercise like yoga or tai chi suits their nature.",
    luckyColors: ["Green", "Yellow", "Brown"],
    luckyNumbers: [2, 5, 8],
    compatibleAnimals: ["Snake", "Rooster", "Rat"],
    incompatibleAnimals: ["Goat"],
  },
  "丙寅": {
    summary: "Bing Yin combines Yang Fire (the blazing sun) with the Tiger's dynamic Wood. This is an explosive, passionate combination — like a forest fire roaring through the jungle. Pure charisma and unstoppable energy.",
    personality: ["Charismatic and naturally commanding attention", "Fearless risk-taker with boundless optimism", "Impulsive but quick to recover from setbacks", "Generous and protective of loved ones"],
    career: "丙寅 individuals are born leaders. They thrive in high-visibility roles like politics, entertainment, sales leadership, and entrepreneurship. Their ability to inspire others makes them exceptional team builders and motivators.",
    love: "In love, 丙寅 people are passionate and dramatic. They court with grand gestures and expect the same level of enthusiasm from their partner. They need someone who can handle their intensity and give them space when needed.",
    health: "Watch for heart and circulation issues (Fire element). Stress management is crucial as they tend to overextend themselves. Cooling activities like swimming or meditation help balance their fire.",
    luckyColors: ["Red", "Green", "Purple"],
    luckyNumbers: [3, 7, 9],
    compatibleAnimals: ["Horse", "Dog", "Pig"],
    incompatibleAnimals: ["Monkey"],
  },
  "丁卯": {
    summary: "Ding Mao combines Yin Fire (the candle flame) with the Rabbit's gentle Wood. This is a refined, artistic combination — like a carefully tended candle in a peaceful garden. Grace, sensitivity, and quiet strength.",
    personality: ["Elegant and refined with a gentle demeanor", "Deeply intuitive and emotionally perceptive", "Artistically gifted with a love for beauty", "Diplomatic and skilled at creating harmony"],
    career: "丁卯 people excel in creative and diplomatic fields. They thrive as artists, designers, counselors, diplomats, and interior decorators. Their attention to aesthetics and harmony makes them valuable in any creative industry.",
    love: "In relationships, 丁卯 individuals are tender and attentive partners. They seek deep emotional connections and create warm, beautiful homes. They are most compatible with partners who appreciate gentleness and artistic sensibility.",
    health: "Focus on liver and eye health (Wood energy). The Fire element needs nourishment — avoid overexertion. Gentle exercise, plenty of rest, and a diet rich in leafy greens support their wellbeing.",
    luckyColors: ["Red", "Pink", "Green"],
    luckyNumbers: [2, 4, 7],
    compatibleAnimals: ["Goat", "Pig", "Dog"],
    incompatibleAnimals: ["Rooster"],
  },
  "戊辰": {
    summary: "Wu Chen combines Yang Earth (the great mountain) with the Dragon's transformative Earth. This is a powerful, stabilizing combination — like a mountain range awakening with volcanic energy. Solid yet dynamic.",
    personality: ["Commanding presence with natural authority", "Ambitious and determined with unwavering focus", "Generous leader who inspires loyalty in others", "Practical visionary who turns ideas into reality"],
    career: "Wu Chen people are natural executives and leaders. They excel in real estate, construction, banking, government, and any role requiring decisiveness and stability. Their ability to manage large responsibilities is unmatched.",
    love: "In relationships, 戊辰 individuals are protective and devoted. They take commitment seriously and provide unwavering support to their partners. They need someone who respects their ambition while offering emotional warmth.",
    health: "Pay attention to digestion, spleen, and stomach health (double Earth). The Earth element needs moderate exercise to stay balanced. Regular routines and a stable lifestyle are essential for wellbeing.",
    luckyColors: ["Yellow", "Brown", "Gold"],
    luckyNumbers: [5, 8, 10],
    compatibleAnimals: ["Rat", "Monkey", "Rooster"],
    incompatibleAnimals: ["Dog"],
  },
  "己巳": {
    summary: "Ji Si combines Yin Earth (the fertile soil) with the Snake's Fire. This is a sophisticated, strategic combination — like rich soil warmed by the sun, nurturing hidden potential. Wisdom and adaptability.",
    personality: ["Wise and intuitive with a strategic mindset", "Elegant and refined, with a mysterious aura", "Highly adaptable and resourceful in challenges", "Deep thinker who values knowledge and learning"],
    career: "己巳 people thrive in roles requiring intellect and strategy. They excel in research, finance, law, philosophy, and consulting. Their ability to read situations and people makes them exceptional negotiators and advisors.",
    love: "In relationships, 己巳 individuals are passionate and deeply committed. They seek intellectual and emotional depth in their partners. They are loyal but need mental stimulation to stay engaged.",
    health: "Focus on heart and circulatory health (Fire branch). The Earth element needs balance — avoid overthinking and worry. Meditation, a balanced diet, and regular sleep patterns support their health.",
    luckyColors: ["Yellow", "Red", "Orange"],
    luckyNumbers: [6, 9, 2],
    compatibleAnimals: ["Ox", "Rooster", "Monkey"],
    incompatibleAnimals: ["Pig"],
  },
  "庚午": {
    summary: "Geng Wu combines Yang Metal (the raw ore) with the Horse's Fire. This is a bold, striking combination — like forged steel glowing with heat. Determination meets passion in a powerful expression of will.",
    personality: ["Strong-willed and fiercely independent", "Passionate about their beliefs and causes", "Natural leader with a competitive edge", "Direct and honest to a fault"],
    career: "Geng Wu individuals excel in competitive, high-stakes environments. They thrive in finance, law, military, sports, and executive leadership. Their combination of discipline and passion drives them to the top of their field.",
    love: "In love, 庚午 people are intense and devoted. They seek partners who can match their passion and respect their independence. When committed, they are fiercely loyal and protective.",
    health: "Watch for lung and respiratory health (Metal element). The Horse's Fire can lead to burnout. Regular exercise, adequate rest, and stress management are essential for maintaining balance.",
    luckyColors: ["White", "Gold", "Red"],
    luckyNumbers: [7, 4, 9],
    compatibleAnimals: ["Tiger", "Goat", "Dog"],
    incompatibleAnimals: ["Rat"],
  },
  "辛未": {
    summary: "Xin Wei combines Yin Metal (the polished jade) with the Goat's Earth. This is a refined, artistic combination — like a beautiful gem resting on fertile ground. Creativity meets stability.",
    personality: ["Artistic and refined with a keen eye for beauty", "Compassionate and deeply empathetic", "Patient and persistent in pursuing their vision", "Elegant in expression, diplomatic in conflict"],
    career: "辛未 people shine in creative and helping professions. They excel as artists, musicians, counselors, educators, and luxury brand professionals. Their combination of aesthetic sense and empathy makes them exceptional in people-oriented roles.",
    love: "In relationships, 辛未 individuals are tender and devoted partners. They create beautiful, nurturing homes and seek emotional depth in their connections. They need partners who appreciate their sensitivity and creative spirit.",
    health: "Focus on digestive health and the spleen (Earth branch). The Metal element requires attention to respiratory health. Creative expression and time in nature are essential for their wellbeing.",
    luckyColors: ["White", "Yellow", "Pastels"],
    luckyNumbers: [8, 2, 6],
    compatibleAnimals: ["Rabbit", "Horse", "Pig"],
    incompatibleAnimals: ["Ox"],
  },
  "壬申": {
    summary: "Ren Shen combines Yang Water (the vast ocean) with the Monkey's Metal. This is a brilliant, expansive combination — like a wide river flowing through mountainous terrain. Intelligence meets adaptability.",
    personality: ["Exceptionally bright and quick-thinking", "Highly adaptable and versatile in any situation", "Innovative with a natural talent for strategy", "Charismatic and persuasive communicator"],
    career: "壬申 people excel in roles requiring intelligence and adaptability. They thrive in technology, finance, engineering, consulting, and entrepreneurship. Their ability to see patterns and solve complex problems makes them invaluable.",
    love: "In relationships, 壬申 individuals are charming and engaging partners. They need intellectual stimulation and variety. They are most compatible with partners who can keep up with their active mind and give them freedom.",
    health: "Focus on kidney and urinary health (Water element). The Metal branch supports lung health. Regular vigorous exercise and plenty of water help maintain their vitality.",
    luckyColors: ["Blue", "Black", "White"],
    luckyNumbers: [1, 9, 4],
    compatibleAnimals: ["Rat", "Dragon", "Snake"],
    incompatibleAnimals: ["Tiger"],
  },
  "癸酉": {
    summary: "Gui You combines Yin Water (the gentle rain) with the Rooster's Metal. This is a perceptive, precise combination — like dewdrops on polished metal. Intuition meets refinement.",
    personality: ["Keenly perceptive with exceptional attention to detail", "Intuitive and emotionally intelligent", "Disciplined and organized in their approach", "Elegant communicator with a sharp wit"],
    career: "癸酉 people thrive in roles requiring precision and insight. They excel in analysis, journalism, medicine, quality control, and the arts. Their meticulous nature makes them excellent editors, critics, and craftspeople.",
    love: "In relationships, 癸酉 individuals are discerning and devoted. They have high standards but are deeply loyal once committed. They seek partners who share their values and appreciate their refined sensibilities.",
    health: "Focus on respiratory health (Metal branch) and kidney health (Water stem). Regular routines, clean living environments, and breathing exercises support their wellbeing.",
    luckyColors: ["Black", "White", "Silver"],
    luckyNumbers: [6, 10, 4],
    compatibleAnimals: ["Ox", "Snake", "Dragon"],
    incompatibleAnimals: ["Rabbit"],
  },
  "甲戌": {
    summary: "Jia Xu combines Yang Wood (the towering tree) with the Dog's Earth. This is a principled, grounded combination — like a mighty oak rooted in loyal soil. Strength of character and unwavering integrity.",
    personality: ["Strong moral compass with unwavering principles", "Loyal and protective of family and friends", "Practical idealist who values justice", "Resilient and determined in the face of adversity"],
    career: "甲戌 people excel in roles requiring integrity and leadership. They thrive in law, social work, military, education, and non-profit leadership. Their commitment to justice makes them natural advocates and protectors.",
    love: "In relationships, 甲戌 individuals are faithful and devoted partners. They value loyalty above all else and are slow to trust but unwavering once committed. They need partners who share their values.",
    health: "Focus on digestive health (Earth branch) and liver health (Wood stem). Regular exercise routines and stress management are important. Time in nature helps maintain emotional balance.",
    luckyColors: ["Green", "Yellow", "Brown"],
    luckyNumbers: [3, 5, 8],
    compatibleAnimals: ["Tiger", "Rabbit", "Horse"],
    incompatibleAnimals: ["Dragon"],
  },
  "乙亥": {
    summary: "Yi Hai combines Yin Wood (the flowering vine) with the Pig's Water. This is a flowing, compassionate combination — like water nourishing a growing plant. Kindness, creativity, and emotional depth.",
    personality: ["Deeply compassionate and empathetic toward others", "Creative with a rich inner world", "Intuitive and spiritually inclined", "Easygoing yet determined when inspired"],
    career: "Yi Hai people excel in creative and helping professions. They thrive in the arts, counseling, education, spirituality, and environmental work. Their ability to nurture growth in others makes them beloved teachers and healers.",
    love: "In relationships, 乙亥 individuals are gentle and devoted partners. They give generously of their time and emotional energy. They need partners who appreciate their sensitivity and provide emotional security.",
    health: "Focus on kidney health (Water branch) and liver health (Wood stem). The Water element supports overall vitality. Time near water, creative expression, and adequate rest support their wellbeing.",
    luckyColors: ["Green", "Blue", "Black"],
    luckyNumbers: [2, 1, 6],
    compatibleAnimals: ["Goat", "Rabbit", "Tiger"],
    incompatibleAnimals: ["Snake"],
  },
  "丙子": {
    summary: "Bing Zi combines Yang Fire (the blazing sun) with the Rat's Water. This is a dynamic, magnetic combination — like a fire burning on water. Charm, intelligence, and emotional depth.",
    personality: ["Magnetic personality that draws others in", "Quick-witted and emotionally intelligent", "Passionate but balanced by冷静沉着", "Natural communicator and storyteller"],
    career: "丙子 individuals excel in communication and people-oriented roles. They thrive in media, sales, education, entertainment, and public relations. Their ability to connect with diverse audiences makes them exceptional communicators.",
    love: "In relationships, 丙子 people are romantic and engaging partners. They bring warmth and excitement to their relationships. They need partners who appreciate their social nature while providing emotional stability.",
    health: "Balance is key for 丙子 — the Fire-Water dynamic can create internal tension. Focus on heart and kidney health. Moderate exercise like swimming, yoga, or tai chi helps harmonize opposing energies.",
    luckyColors: ["Red", "Blue", "Black"],
    luckyNumbers: [1, 3, 6],
    compatibleAnimals: ["Ox", "Dragon", "Monkey"],
    incompatibleAnimals: ["Horse"],
  },
  "丁丑": {
    summary: "Ding Chou combines Yin Fire (the candle flame) with the Ox's Earth. This is a steady, warming combination — like a hearth fire in a solid home. Warmth, reliability, and quiet strength.",
    personality: ["Dependable and warm-hearted", "Methodical with a gentle touch", "Patient teacher and natural mentor", "Loyal friend and devoted family member"],
    career: "丁丑 people thrive in roles that combine care with structure. They excel in healthcare, education, social work, hospitality, and craftsmanship. Their patient, methodical approach makes them excellent mentors and caregivers.",
    love: "In relationships, 丁丑 individuals are steadfast and loving partners. They express love through actions rather than words, providing consistent support. They value security and create warm, stable homes.",
    health: "Focus on digestive health (Earth branch). The Fire element needs balance — avoid emotional extremes. Regular routines, warm meals, and gentle exercise support their constitution.",
    luckyColors: ["Red", "Yellow", "Brown"],
    luckyNumbers: [2, 5, 8],
    compatibleAnimals: ["Snake", "Rooster", "Rat"],
    incompatibleAnimals: ["Goat"],
  },
  "戊寅": {
    summary: "Wu Yin combines Yang Earth (the great mountain) with the Tiger's Wood. This is a bold, expansive combination — like a mountain forest reaching for the sky. Authority tempered with adventure.",
    personality: ["Natural authority with an adventurous spirit", "Confident decision-maker who takes calculated risks", "Generous leader who empowers others", "Ambitious yet grounded in practical reality"],
    career: "Wu Yin people excel in leadership roles that require both vision and execution. They thrive in management, real estate, construction, military, and government. Their ability to build and lead teams is exceptional.",
    love: "In relationships, 戊寅 individuals are protective and passionate. They bring stability and excitement in equal measure. They need partners who respect their independence while offering emotional warmth.",
    health: "Focus on digestive and liver health (Earth-Wood dynamic). Regular exercise and stress management are important. Outdoor activities like hiking help balance their energies.",
    luckyColors: ["Yellow", "Green", "Brown"],
    luckyNumbers: [5, 3, 8],
    compatibleAnimals: ["Horse", "Dog", "Pig"],
    incompatibleAnimals: ["Monkey"],
  },
  "己卯": {
    summary: "Ji Mao combines Yin Earth (the fertile soil) with the Rabbit's Wood. This is a gentle, nurturing combination — like a cultivated garden in perfect balance. Diplomacy and artistic sensibility.",
    personality: ["Diplomatic and skilled at creating harmony", "Artistically inclined with a refined aesthetic", "Nurturing and supportive of others' growth", "Peaceful yet quietly determined"],
    career: "己卯 people excel in creative and diplomatic fields. They thrive as designers, counselors, mediators, educators, and in the beauty industry. Their ability to create harmony makes them valuable team members and leaders.",
    love: "In relationships, 己卯 individuals are gentle and attentive partners. They seek peace and harmony in their relationships and are skilled at resolving conflicts. They need calm, stable partners who appreciate their nurturing nature.",
    health: "Focus on liver health (Wood branch) and digestive health (Earth stem). Gentle exercise like yoga, pilates, or walking supports their wellbeing. A balanced diet with plenty of vegetables is recommended.",
    luckyColors: ["Yellow", "Green", "Pink"],
    luckyNumbers: [2, 4, 8],
    compatibleAnimals: ["Goat", "Pig", "Dog"],
    incompatibleAnimals: ["Rooster"],
  },
  "庚辰": {
    summary: "Geng Chen combines Yang Metal (the raw ore) with the Dragon's Earth. This is a formidable, powerful combination — like metal veins running through bedrock. Strength, ambition, and transformative power.",
    personality: ["Strong-willed with a commanding presence", "Ambitious and driven to achieve greatness", "Confident decision-maker with sharp instincts", "Natural leader who commands respect"],
    career: "庚辰 people are built for leadership and influence. They excel in finance, law, military, engineering, and executive roles. Their combination of analytical sharpness and practical wisdom drives them to positions of power.",
    love: "In relationships, 庚辰 individuals are intense and devoted. They seek partners who can match their ambition and strength. Once committed, they are fiercely loyal and protective.",
    health: "Focus on lung and digestive health (Metal-Earth). The double Earth provides strong constitution but can lead to stagnation. Regular vigorous exercise and a high-fiber diet support their health.",
    luckyColors: ["White", "Gold", "Yellow"],
    luckyNumbers: [7, 5, 8],
    compatibleAnimals: ["Rat", "Monkey", "Rooster"],
    incompatibleAnimals: ["Dog"],
  },
  "辛巳": {
    summary: "Xin Si combines Yin Metal (the polished jade) with the Snake's Fire. This is a refined, strategic combination — like a finely crafted blade warmed by fire. Intelligence meets elegance.",
    personality: ["Keenly intelligent with a strategic mind", "Elegant and sophisticated in manner", "Mysterious and intuitively perceptive", "Ambitious with a clear sense of purpose"],
    career: "辛巳 people excel in roles requiring intellect and refinement. They thrive in research, finance, law, consulting, and luxury industries. Their strategic thinking and attention to detail make them exceptional analysts and advisors.",
    love: "In relationships, 辛巳 individuals are passionate and discerning. They seek deep intellectual and emotional connections. They are loyal but selective, and need partners who stimulate their minds.",
    health: "Focus on heart and respiratory health (Fire-Metal dynamic). Stress management is crucial. Practices like meditation, deep breathing, and moderate exercise help maintain balance.",
    luckyColors: ["White", "Red", "Gold"],
    luckyNumbers: [6, 9, 4],
    compatibleAnimals: ["Ox", "Rooster", "Monkey"],
    incompatibleAnimals: ["Pig"],
  },
  "壬午": {
    summary: "Ren Wu combines Yang Water (the vast ocean) with the Horse's Fire. This is a passionate, expansive combination — like steam rising from hot springs. Visionary energy meets unstoppable drive.",
    personality: ["Passionate and driven with a visionary outlook", "Charismatic and naturally inspiring to others", "Independent and freedom-loving", "Emotional depth combined with bold action"],
    career: "壬午 people thrive in dynamic, high-visibility roles. They excel in entertainment, politics, sports, entrepreneurship, and creative direction. Their ability to inspire and lead makes them natural figures of influence.",
    love: "In relationships, 壬午 individuals are romantic and intense. They bring passion and excitement to their partnerships. They need partners who respect their need for freedom while matching their emotional depth.",
    health: "Focus on kidney and heart health (Water-Fire balance). This combination needs careful harmony — avoid emotional extremes. Swimming, moderate exercise, and relaxation practices support wellbeing.",
    luckyColors: ["Blue", "Red", "Black"],
    luckyNumbers: [1, 9, 7],
    compatibleAnimals: ["Tiger", "Goat", "Dog"],
    incompatibleAnimals: ["Rat"],
  },
  "癸未": {
    summary: "Gui Wei combines Yin Water (the gentle rain) with the Goat's Earth. This is a nurturing, creative combination — like rain falling on fertile fields. Emotional depth meets artistic expression.",
    personality: ["Deeply creative with a rich emotional inner world", "Compassionate and intuitively understanding", "Patient and persistent in pursuing dreams", "Gentle yet resilient in adversity"],
    career: "癸未 people excel in creative and healing professions. They thrive in the arts, counseling, education, spiritual guidance, and environmental work. Their empathy and creativity make them exceptional in people-oriented fields.",
    love: "In relationships, 癸未 individuals are tender and devoted partners. They seek emotional depth and creative connection. They need partners who appreciate their sensitivity and provide stable emotional support.",
    health: "Focus on kidney and digestive health (Water-Earth). Emotional wellbeing is closely tied to physical health for 癸未. Creative expression, time in nature, and a balanced diet are essential.",
    luckyColors: ["Blue", "Black", "Yellow"],
    luckyNumbers: [8, 2, 6],
    compatibleAnimals: ["Rabbit", "Horse", "Pig"],
    incompatibleAnimals: ["Ox"],
  },
  "甲申": {
    summary: "Jia Shen combines Yang Wood (the towering tree) with the Monkey's Metal. This is a brilliant, unconventional combination — like an ironwood tree that bends but never breaks. Innovation meets determination.",
    personality: ["Exceptionally innovative with a brilliant mind", "Independent thinker who challenges conventions", "Charismatic and persuasive communicator", "Resourceful problem-solver in any situation"],
    career: "甲申 people excel in cutting-edge and innovative fields. They thrive in technology, engineering, finance, research, and entrepreneurship. Their ability to think differently makes them natural innovators and disruptors.",
    love: "In relationships, 甲申 individuals are stimulating and engaging partners. They need intellectual challenge and variety. They are most compatible with partners who appreciate their independence and sharp wit.",
    health: "Focus on liver and lung health (Wood-Metal dynamic). The creative tension between these elements needs release through regular exercise and creative expression. Breathing exercises are particularly beneficial.",
    luckyColors: ["Green", "White", "Blue"],
    luckyNumbers: [3, 7, 4],
    compatibleAnimals: ["Rat", "Dragon", "Snake"],
    incompatibleAnimals: ["Tiger"],
  },
  "乙酉": {
    summary: "Yi You combines Yin Wood (the flowering vine) with the Rooster's Metal. This is a precise, determined combination — like a vine climbing a metal trellis. Grace meets discipline.",
    personality: ["Disciplined and precise with high personal standards", "Elegant and refined in appearance and manner", "Determined and persistent in achieving goals", "Keen observer with excellent attention to detail"],
    career: "乙酉 people thrive in roles requiring precision and aesthetic sense. They excel in design, editing, quality assurance, fashion, law, and craftsmanship. Their meticulous nature and high standards drive excellence.",
    love: "In relationships, 乙酉 individuals are discerning and devoted. They have high standards but are deeply loyal once committed. They seek partners who share their values and appreciate their refined nature.",
    health: "Focus on respiratory health (Metal branch) and liver health (Wood stem). Regular routines, clean environments, and moderate exercise support their wellbeing. Avoid过度劳累.",
    luckyColors: ["Green", "White", "Gold"],
    luckyNumbers: [2, 6, 4],
    compatibleAnimals: ["Ox", "Snake", "Dragon"],
    incompatibleAnimals: ["Rabbit"],
  },
  "丙戌": {
    summary: "Bing Xu combines Yang Fire (the blazing sun) with the Dog's Earth. This is a loyal, warm combination — like a campfire on solid ground. Fierce loyalty and unwavering principles.",
    personality: ["Fiercely loyal with a strong sense of justice", "Warm-hearted and generous to those they love", "Principled and unwavering in their beliefs", "Natural protector and advocate for others"],
    career: "丙戌 people excel in roles that require loyalty and leadership. They thrive in law, military, social work, education, and community leadership. Their commitment to justice makes them powerful advocates and protectors.",
    love: "In relationships, 丙戌 individuals are devoted and protective partners. They value loyalty above all and are unwavering in their commitment. They need partners who share their values and appreciate their warmth.",
    health: "Focus on heart and digestive health (Fire-Earth). The stable Earth supports their constitution but they need regular exercise to keep Fire energy balanced. Team sports are excellent for them.",
    luckyColors: ["Red", "Yellow", "Brown"],
    luckyNumbers: [3, 5, 8],
    compatibleAnimals: ["Tiger", "Rabbit", "Horse"],
    incompatibleAnimals: ["Dragon"],
  },
  "丁亥": {
    summary: "Ding Hai combines Yin Fire (the candle flame) with the Pig's Water. This is a gentle, intuitive combination — like a lantern reflected in still water. Spiritual depth and emotional wisdom.",
    personality: ["Deeply intuitive with a spiritual nature", "Gentle and compassionate toward all beings", "Wise beyond their years with emotional maturity", "Creative with a rich inner life"],
    career: "丁亥 people excel in spiritual, creative, and healing professions. They thrive as counselors, artists, writers, spiritual teachers, and in philanthropic work. Their ability to understand deep emotions makes them exceptional healers.",
    love: "In relationships, 丁亥 individuals are tender and spiritually connected partners. They seek soul-level connections and emotional depth. They need partners who understand their sensitivity and spiritual nature.",
    health: "Focus on kidney and heart health (Water-Fire balance). Emotional health directly affects physical wellbeing. Meditation, time near water, and creative expression are essential for their health.",
    luckyColors: ["Red", "Blue", "Black"],
    luckyNumbers: [2, 1, 6],
    compatibleAnimals: ["Goat", "Rabbit", "Tiger"],
    incompatibleAnimals: ["Snake"],
  },
  "戊子": {
    summary: "Wu Zi combines Yang Earth (the great mountain) with the Rat's Water. This is a stable yet adaptable combination — like an island in a flowing river. Security and resourcefulness in perfect balance.",
    personality: ["Grounded and practical with excellent judgment", "Resourceful and adaptable in changing circumstances", "Natural manager who balances risk and stability", "Wise counselor with a calm presence"],
    career: "Wu Zi people excel in management and advisory roles. They thrive in real estate, finance, consulting, government, and education. Their balanced judgment makes them excellent executives and decision-makers.",
    love: "In relationships, 戊子 individuals are stable and devoted partners. They provide unwavering support and practical care. They seek partners who appreciate their reliability and share their values of security and family.",
    health: "Focus on digestive and kidney health (Earth-Water). The balanced elements give them good constitution. Regular routines, moderate exercise, and a stable lifestyle support their wellbeing.",
    luckyColors: ["Yellow", "Blue", "Brown"],
    luckyNumbers: [5, 1, 8],
    compatibleAnimals: ["Ox", "Dragon", "Monkey"],
    incompatibleAnimals: ["Horse"],
  },
  "己丑": {
    summary: "Ji Chou combines Yin Earth (the fertile soil) with the Ox's Earth. This is double Earth — stable, nurturing, and deeply grounded. Like rich soil in a well-tended field — patient, productive, and enduring.",
    personality: ["Exceptionally dependable and trustworthy", "Patient and persistent with remarkable endurance", "Practical and methodical in all endeavors", "Nurturing and supportive of others' growth"],
    career: "己丑 people thrive in roles requiring stability and persistence. They excel in agriculture, real estate, education, healthcare, and traditional crafts. Their methodical nature makes them excellent long-term planners and builders.",
    love: "In relationships, 己丑 individuals are loyal and steadfast partners. They express love through consistent care and practical support. They seek lasting commitment and create deeply stable, nurturing homes.",
    health: "Focus on digestive and spleen health (double Earth). The strong Earth element can lead to stagnation. Regular exercise, a varied diet, and staying hydrated are essential for maintaining health.",
    luckyColors: ["Yellow", "Brown", "Orange"],
    luckyNumbers: [5, 8, 2],
    compatibleAnimals: ["Snake", "Rooster", "Rat"],
    incompatibleAnimals: ["Goat"],
  },
  "庚寅": {
    summary: "Geng Yin combines Yang Metal (the raw ore) with the Tiger's Wood. This is a bold, pioneering combination — like an axe carving through virgin forest. Courage, strength, and trailblazing spirit.",
    personality: ["Fearless pioneer who forges new paths", "Strong-willed with unwavering determination", "Natural leader who inspires through action", "Competitive and driven to be the best"],
    career: "庚寅 people excel in competitive and pioneering fields. They thrive in entrepreneurship, military, surgery, engineering, and extreme sports. Their courage and determination drive them to achieve the extraordinary.",
    love: "In relationships, 庚寅 individuals are passionate and protective. They bring excitement and strength to their partnerships. They need partners who can match their intensity while providing emotional grounding.",
    health: "Focus on lung and liver health (Metal-Wood dynamic). This combination creates productive tension. Regular intense exercise, stress management, and avoiding overexertion are important.",
    luckyColors: ["White", "Green", "Gold"],
    luckyNumbers: [7, 3, 4],
    compatibleAnimals: ["Horse", "Dog", "Pig"],
    incompatibleAnimals: ["Monkey"],
  },
  "辛卯": {
    summary: "Xin Mao combines Yin Metal (the polished jade) with the Rabbit's Wood. This is a refined, artistic combination — like a delicate carving in precious wood. Elegance meets creativity.",
    personality: ["Artistically gifted with exquisite taste", "Gentle and diplomatic in communication", "Perceptive with a keen eye for detail", "Elegant and poised under pressure"],
    career: "辛卯 people excel in creative and precision-oriented fields. They thrive in art, design, fashion, music, writing, and luxury goods. Their refined sensibilities and attention to detail make them exceptional craftspeople.",
    love: "In relationships, 辛卯 individuals are romantic and attentive. They appreciate beauty in all forms and create elegant, harmonious relationships. They need partners who share their aesthetic values and gentle nature.",
    health: "Focus on respiratory and liver health (Metal-Wood). Gentle exercise like tai chi, yoga, or pilates suits their nature. A clean, harmonious living environment supports their wellbeing.",
    luckyColors: ["White", "Green", "Pink"],
    luckyNumbers: [4, 2, 7],
    compatibleAnimals: ["Goat", "Pig", "Dog"],
    incompatibleAnimals: ["Rooster"],
  },
  "壬辰": {
    summary: "Ren Chen combines Yang Water (the vast ocean) with the Dragon's Earth. This is a powerful, transformative combination — like water carving through ancient rock. Vision, power, and lasting impact.",
    personality: ["Visionary with the power to enact real change", "Charismatic and naturally commanding", "Deeply intuitive and strategically minded", "Ambitious with a global perspective"],
    career: "壬辰 people are built for influence and transformation. They excel in politics, environmental leadership, large-scale entrepreneurship, philanthropy, and any role that allows them to shape the future.",
    love: "In relationships, 壬辰 individuals are intense and devoted. They seek partners who share their vision and ambition. They are loyal but need independence and intellectual stimulation.",
    health: "Focus on kidney and digestive health (Water-Earth). The powerful Water element needs healthy channels. Swimming, hydration, and stress management are essential for their wellbeing.",
    luckyColors: ["Blue", "Black", "Yellow"],
    luckyNumbers: [1, 5, 8],
    compatibleAnimals: ["Rat", "Monkey", "Rooster"],
    incompatibleAnimals: ["Dog"],
  },
  "癸巳": {
    summary: "Gui Si combines Yin Water (the gentle rain) with the Snake's Fire. This is a mysterious, intuitive combination — like mist rising from a warm spring. Wisdom, depth, and quiet power.",
    personality: ["Deeply intuitive with almost psychic perceptiveness", "Wise and philosophical beyond their years", "Mysterious and intriguing to others", "Elegant and composed in all situations"],
    career: "癸巳 people excel in roles requiring depth and insight. They thrive in research, philosophy, psychology, spirituality, and strategic consulting. Their ability to see beneath the surface makes them exceptional advisors.",
    love: "In relationships, 癸巳 individuals are passionate and deeply committed. They seek profound emotional and spiritual connections. They need partners who respect their depth and give them space for reflection.",
    health: "Focus on kidney and heart health (Water-Fire). This combination needs careful balance. Meditation, moderate exercise, and avoiding emotional extremes support their health.",
    luckyColors: ["Black", "Red", "Purple"],
    luckyNumbers: [6, 2, 9],
    compatibleAnimals: ["Ox", "Rooster", "Monkey"],
    incompatibleAnimals: ["Pig"],
  },
  "甲午": {
    summary: "Jia Wu combines Yang Wood (the towering tree) with the Horse's Fire. This is a vibrant, passionate combination — like a tree in full summer bloom. Growth, warmth, and unstoppable energy.",
    personality: ["Passionate and full of vibrant life energy", "Optimistic with a sunny disposition", "Adventurous and always seeking new experiences", "Generous and warm-hearted to all"],
    career: "甲午 people thrive in dynamic, creative environments. They excel in entertainment, sports, tourism, education, and creative direction. Their enthusiasm and warmth make them natural motivators and team builders.",
    love: "In relationships, 甲午 individuals are romantic and exciting partners. They bring warmth and adventure to their relationships. They need partners who share their zest for life and understand their need for freedom.",
    health: "Focus on liver and heart health (Wood-Fire). This dynamic combination creates abundant energy but risk of burnout. Regular rest, cooling activities, and moderation in all things are essential.",
    luckyColors: ["Green", "Red", "Purple"],
    luckyNumbers: [3, 7, 9],
    compatibleAnimals: ["Tiger", "Goat", "Dog"],
    incompatibleAnimals: ["Rat"],
  },
  "乙未": {
    summary: "Yi Wei combines Yin Wood (the flowering vine) with the Goat's Earth. This is a creative, nurturing combination — like a garden in late summer. Artistic abundance and gentle strength.",
    personality: ["Creative and artistically gifted", "Compassionate and deeply caring toward others", "Patient and persistent in nurturing projects to completion", "Gentle yet resilient in adversity"],
    career: "乙未 people excel in creative and care-oriented professions. They thrive in the arts, education, counseling, healthcare, and environmental work. Their ability to nurture growth in others makes them exceptional teachers and mentors.",
    love: "In relationships, 乙未 individuals are tender and devoted partners. They create warm, nurturing homes and invest deeply in their relationships. They need partners who appreciate their gentle nature and creative spirit.",
    health: "Focus on liver and digestive health (Wood-Earth). Creative expression is essential for their wellbeing. Gentle exercise, time in nature, and a balanced diet support their health.",
    luckyColors: ["Green", "Yellow", "Pastels"],
    luckyNumbers: [8, 2, 5],
    compatibleAnimals: ["Rabbit", "Horse", "Pig"],
    incompatibleAnimals: ["Ox"],
  },
  "丙申": {
    summary: "Bing Shen combines Yang Fire (the blazing sun) with the Monkey's Metal. This is a brilliant, lively combination — like sparks flying from a forge. Intelligence, wit, and dazzling charisma.",
    personality: ["Exceptionally witty and intellectually sharp", "Charismatic and naturally entertaining", "Innovative with a talent for invention", "Adaptable and quick on their feet"],
    career: "丙申 people thrive in roles that reward intelligence and showmanship. They excel in technology, media, entertainment, sales, and entrepreneurship. Their quick minds and charisma make them natural leaders and innovators.",
    love: "In relationships, 丙申 individuals are charming and stimulating partners. They keep relationships exciting with their wit and creativity. They need partners who can match their mental agility and appreciate their social nature.",
    health: "Focus on heart and lung health (Fire-Metal). The dynamic energy needs healthy outlets. Regular exercise, mental stimulation, and adequate rest help maintain their vitality.",
    luckyColors: ["Red", "White", "Gold"],
    luckyNumbers: [3, 7, 9],
    compatibleAnimals: ["Rat", "Dragon", "Snake"],
    incompatibleAnimals: ["Tiger"],
  },
  "丁酉": {
    summary: "Ding You combines Yin Fire (the candle flame) with the Rooster's Metal. This is a refined, luminous combination — like a candle in a crystal lantern. Elegance, precision, and quiet brilliance.",
    personality: ["Exquisite taste with a refined sensibility", "Precise and meticulous in all endeavors", "Elegant communicator with natural charm", "Disciplined yet warm-hearted"],
    career: "丁酉 people excel in roles requiring precision and refinement. They thrive in design, fashion, luxury goods, editing, law, and the arts. Their combination of elegance and discipline makes them exceptional in their chosen field.",
    love: "In relationships, 丁酉 individuals are romantic and devoted. They have high standards and appreciate beauty in their partnerships. They seek partners who share their refined sensibilities and values.",
    health: "Focus on heart and respiratory health (Fire-Metal). Regular routines and clean living environments are important. Gentle exercise, breathing practices, and stress management support their wellbeing.",
    luckyColors: ["Red", "White", "Gold"],
    luckyNumbers: [2, 4, 6],
    compatibleAnimals: ["Ox", "Snake", "Dragon"],
    incompatibleAnimals: ["Rabbit"],
  },
  "戊戌": {
    summary: "Wu Xu combines Yang Earth (the great mountain) with the Dog's Earth. This is double Earth — solid, principled, and unshakeable. Like a mountain fortress — loyal, protective, and enduring.",
    personality: ["Unwaveringly loyal with a strong sense of duty", "Dependable and trustworthy in all matters", "Principled with an unshakeable moral code", "Patient and persistent beyond measure"],
    career: "Wu Xu people are built for roles requiring integrity and stability. They excel in law, military, government, finance, and any position of trust. Their unwavering principles make them natural guardians of institutions.",
    love: "In relationships, 戊戌 individuals are faithful and protective partners. They take commitment very seriously and provide unwavering support. They need partners who share their values and appreciate their steadfast nature.",
    health: "Focus on digestive health (double Earth). The strong Earth can lead to stagnation or heavy energy. Regular vigorous exercise, a varied diet, and staying mentally stimulated are essential.",
    luckyColors: ["Yellow", "Brown", "Gold"],
    luckyNumbers: [5, 8, 10],
    compatibleAnimals: ["Tiger", "Rabbit", "Horse"],
    incompatibleAnimals: ["Dragon"],
  },
  "己亥": {
    summary: "Ji Hai combines Yin Earth (the fertile soil) with the Pig's Water. This is a flowing, receptive combination — like a river delta nourishing rich farmland. Generosity, intuition, and emotional wisdom.",
    personality: ["Generous and giving to a fault", "Deeply intuitive with emotional wisdom", "Adaptable and easygoing in most situations", "Creative with a rich inner landscape"],
    career: "己亥 people excel in helping and creative professions. They thrive in philanthropy, counseling, education, the arts, and spiritual guidance. Their ability to nurture and understand others makes them beloved in their communities.",
    love: "In relationships, 己亥 individuals are giving and devoted partners. They seek emotional depth and spiritual connection. They need partners who appreciate their generosity while providing stable grounding.",
    health: "Focus on digestive and kidney health (Earth-Water). Emotional health directly affects physical wellbeing. Time in nature, creative expression, and a balanced lifestyle support their health.",
    luckyColors: ["Yellow", "Blue", "Black"],
    luckyNumbers: [5, 1, 8],
    compatibleAnimals: ["Goat", "Rabbit", "Tiger"],
    incompatibleAnimals: ["Snake"],
  },
  "庚子": {
    summary: "Geng Zi combines Yang Metal (the raw ore) with the Rat's Water. This is a sharp, intelligent combination — like a steel blade tempered in cold water. Mental clarity and strategic brilliance.",
    personality: ["Exceptionally sharp-minded and analytical", "Strategic thinker with excellent judgment", "Independent and self-reliant", "Ambitious with a competitive edge"],
    career: "庚子 people excel in roles requiring mental sharpness and strategy. They thrive in finance, law, technology, research, and entrepreneurship. Their analytical minds make them exceptional problem-solvers and strategists.",
    love: "In relationships, 庚子 individuals are loyal and discerning. They seek intellectual stimulation and value honesty above all. They need partners who can engage their minds and respect their independence.",
    health: "Focus on lung and kidney health (Metal-Water). This combination supports mental clarity but can lead to overthinking. Regular exercise, meditation, and adequate rest are essential for balance.",
    luckyColors: ["White", "Blue", "Black"],
    luckyNumbers: [7, 1, 4],
    compatibleAnimals: ["Ox", "Dragon", "Monkey"],
    incompatibleAnimals: ["Horse"],
  },
  "辛丑": {
    summary: "Xin Chou combines Yin Metal (the polished jade) with the Ox's Earth. This is a refined, industrious combination — like a gem embedded in solid rock. Precision meets perseverance.",
    personality: ["Industrious and diligent with high standards", "Refined tastes and elegant sensibilities", "Patient and methodical in all pursuits", "Reliable and trustworthy in every commitment"],
    career: "辛丑 people thrive in roles requiring precision and dedication. They excel in craftsmanship, accounting, engineering, law, and quality management. Their meticulous nature and high standards drive excellence in everything they do.",
    love: "In relationships, 辛丑 individuals are loyal and devoted partners. They express love through consistent care and practical actions. They seek partners who share their values and appreciate their steady nature.",
    health: "Focus on respiratory and digestive health (Metal-Earth). Regular routines and moderate exercise suit their nature. A clean, organized living environment supports their wellbeing.",
    luckyColors: ["White", "Yellow", "Brown"],
    luckyNumbers: [6, 8, 4],
    compatibleAnimals: ["Snake", "Rooster", "Rat"],
    incompatibleAnimals: ["Goat"],
  },
  "壬寅": {
    summary: "Ren Yin combines Yang Water (the vast ocean) with the Tiger's Wood. This is a powerful, adventurous combination — like a wild river through a primeval forest. Freedom, courage, and raw natural force.",
    personality: ["Adventurous spirit with unbounded courage", "Independent and fiercely自由", "Charismatic natural leader", "Deeply intuitive with a pioneer's vision"],
    career: "壬寅 people thrive in dynamic, adventurous fields. They excel in exploration, entrepreneurship, environmental leadership, sports, and any role that requires bold action and vision.",
    love: "In relationships, 壬寅 individuals are passionate and exciting partners. They bring adventure and depth to their relationships. They need partners who respect their need for freedom and share their love of exploration.",
    health: "Focus on kidney and liver health (Water-Wood). This flowing combination has abundant energy. Regular outdoor exercise, adequate hydration, and stress management support their vitality.",
    luckyColors: ["Blue", "Green", "Black"],
    luckyNumbers: [1, 3, 9],
    compatibleAnimals: ["Horse", "Dog", "Pig"],
    incompatibleAnimals: ["Monkey"],
  },
  "癸卯": {
    summary: "Gui Mao combines Yin Water (the gentle rain) with the Rabbit's Wood. This is a gentle, artistic combination — like rain nourishing a bamboo garden. Sensitivity, grace, and quiet strength.",
    personality: ["Gentle and graceful with artistic sensibilities", "Deeply intuitive and emotionally perceptive", "Diplomatic and skilled at creating harmony", "Quietly determined and resilient"],
    career: "癸卯 people excel in creative and diplomatic professions. They thrive in the arts, counseling, mediation, education, and design. Their sensitivity and perceptiveness make them exceptional in roles requiring emotional intelligence.",
    love: "In relationships, 癸卯 individuals are tender and romantic partners. They seek deep emotional connections and create harmonious homes. They need partners who appreciate their sensitivity and provide emotional security.",
    health: "Focus on kidney and liver health (Water-Wood). Gentle exercise like tai chi, yoga, or walking suits their nature. Time near water and in nature is essential for their wellbeing.",
    luckyColors: ["Blue", "Green", "Black"],
    luckyNumbers: [2, 4, 1],
    compatibleAnimals: ["Goat", "Pig", "Dog"],
    incompatibleAnimals: ["Rooster"],
  },
  "甲辰": {
    summary: "Jia Chen combines Yang Wood (the towering tree) with the Dragon's Earth. This is a dynamic, transformative combination — like a great tree breaking through rocky soil. Ambitious growth meets transformative power.",
    personality: ["Ambitious with a vision for grand achievements", "Charismatic and naturally commanding attention", "Innovative and unafraid of radical change", "Confident leader with a generous spirit"],
    career: "甲辰 people are built for leadership and transformation. They excel in entrepreneurship, executive roles, environmental leadership, education, and any field where they can drive significant change.",
    love: "In relationships, 甲辰 individuals are passionate and devoted. They seek partners who share their vision and ambition. They are loyal but need independence and intellectual stimulation.",
    health: "Focus on liver and digestive health (Wood-Earth). The dynamic tension needs healthy outlets. Regular exercise, stress management, and a balanced diet support their wellbeing.",
    luckyColors: ["Green", "Yellow", "Gold"],
    luckyNumbers: [3, 5, 8],
    compatibleAnimals: ["Rat", "Monkey", "Rooster"],
    incompatibleAnimals: ["Dog"],
  },
  "乙巳": {
    summary: "Yi Si combines Yin Wood (the flowering vine) with the Snake's Fire. This is a graceful, passionate combination — like flowering vines warmed by the sun. Beauty, intelligence, and hidden depth.",
    personality: ["Elegant and refined with a passionate core", "Intelligent with a strategic, perceptive mind", "Diplomatic and charming in social situations", "Mysterious with hidden depths of wisdom"],
    career: "乙巳 people thrive in roles requiring both creativity and strategy. They excel in design, consulting, law, diplomacy, and the arts. Their combination of grace and intellect makes them exceptional in leadership.",
    love: "In relationships, 乙巳 individuals are passionate and perceptive partners. They seek deep emotional and intellectual connections. They need partners who appreciate their complexity and give them space for growth.",
    health: "Focus on liver and heart health (Wood-Fire). The rising energy needs careful management. Cooling activities, meditation, and moderation in all things support their health.",
    luckyColors: ["Green", "Red", "Purple"],
    luckyNumbers: [2, 6, 9],
    compatibleAnimals: ["Ox", "Rooster", "Monkey"],
    incompatibleAnimals: ["Pig"],
  },
  "丙午": {
    summary: "Bing Wu combines Yang Fire (the blazing sun) with the Horse's Fire. This is double Fire — the most intense, passionate combination in the calendar. Like the sun at noon in high summer — radiant, powerful, and unstoppable.",
    personality: ["Passionate and radiant with magnetic charisma", "Bold and fearless in pursuing their goals", "Natural leader who inspires multitudes", "Independent and fiercely自由"],
    career: "丙午 people are built for greatness on the world stage. They excel in entertainment, politics, sports, entrepreneurship, and creative direction. Their charisma and drive can move mountains.",
    love: "In relationships, 丙午 individuals are intensely romantic and passionate. They love deeply and dramatically. They need partners who can handle their intensity and give them the freedom they crave.",
    health: "Focus on heart health (double Fire). This combination generates tremendous heat — both physical and emotional. Cooling activities, stress management, and avoiding overexertion are critical.",
    luckyColors: ["Red", "Purple", "Gold"],
    luckyNumbers: [3, 7, 9],
    compatibleAnimals: ["Tiger", "Goat", "Dog"],
    incompatibleAnimals: ["Rat"],
  },
  "丁未": {
    summary: "Ding Wei combines Yin Fire (the candle flame) with the Goat's Earth. This is a warm, nurturing combination — like a gentle hearth in a cozy home. Kindness, creativity, and steady warmth.",
    personality: ["Warm-hearted and nurturing toward others", "Creative with a gentle artistic spirit", "Compassionate and deeply empathetic", "Patient and devoted to loved ones"],
    career: "丁未 people excel in caring and creative professions. They thrive in healthcare, education, the arts, social work, and hospitality. Their warm, nurturing nature makes them beloved colleagues and leaders.",
    love: "In relationships, 丁未 individuals are tender and devoted partners. They create warm, nurturing homes and invest deeply in their relationships. They need partners who appreciate their gentleness and reciprocate their care.",
    health: "Focus on heart and digestive health (Fire-Earth). The stable Earth supports their constitution. Regular routines, gentle exercise, and a warm, balanced diet support their wellbeing.",
    luckyColors: ["Red", "Yellow", "Orange"],
    luckyNumbers: [2, 5, 8],
    compatibleAnimals: ["Rabbit", "Horse", "Pig"],
    incompatibleAnimals: ["Ox"],
  },
  "戊申": {
    summary: "Wu Shen combines Yang Earth (the great mountain) with the Monkey's Metal. This is a strong, intelligent combination — like a mountain rich with precious ores. Stability meets brilliance.",
    personality: ["Intelligent and practical with excellent judgment", "Confident leader with a strategic mind", "Resourceful and adaptable in challenges", "Generous mentor who builds others up"],
    career: "Wu Shen people excel at the intersection of strategy and execution. They thrive in consulting, engineering, finance, technology leadership, and entrepreneurship. Their balanced judgment and intelligence make them exceptional leaders.",
    love: "In relationships, 戊申 individuals are loyal and stimulating partners. They seek intellectual companionship and emotional stability. They need partners who appreciate their wisdom and share their values.",
    health: "Focus on digestive and respiratory health (Earth-Metal). Regular exercise, mental stimulation, and a balanced diet support their health. They benefit from variety in their routines.",
    luckyColors: ["Yellow", "White", "Gold"],
    luckyNumbers: [5, 7, 4],
    compatibleAnimals: ["Rat", "Dragon", "Snake"],
    incompatibleAnimals: ["Tiger"],
  },
  "己酉": {
    summary: "Ji You combines Yin Earth (the fertile soil) with the Rooster's Metal. This is a refined, productive combination — like a well-tended field yielding golden harvest. Discipline meets nurturing abundance.",
    personality: ["Disciplined and organized with a nurturing touch", "Refined sensibilities and high standards", "Dependable and trustworthy in all matters", "Patient teacher and natural mentor"],
    career: "己酉 people thrive in roles requiring organization and care. They excel in education, healthcare, finance, quality management, and the arts. Their combination of discipline and warmth makes them exceptional leaders.",
    love: "In relationships, 己酉 individuals are faithful and attentive partners. They express love through thoughtful actions and consistent support. They seek partners who share their values and appreciate their steadfast nature.",
    health: "Focus on digestive and respiratory health (Earth-Metal). Regular routines and a clean environment support their wellbeing. Moderate exercise and a balanced diet are essential.",
    luckyColors: ["Yellow", "White", "Gold"],
    luckyNumbers: [8, 6, 4],
    compatibleAnimals: ["Ox", "Snake", "Dragon"],
    incompatibleAnimals: ["Rabbit"],
  },
  "庚戌": {
    summary: "Geng Xu combines Yang Metal (the raw ore) with the Dog's Earth. This is a loyal, strong combination — like iron forged into armor. Protection, duty, and unwavering strength.",
    personality: ["Fiercely loyal with a protector's heart", "Strong-willed and principled", "Dependable and responsible beyond measure", "Courageous in defending others"],
    career: "庚戌 people are built for roles requiring strength and integrity. They excel in law enforcement, military, law, security, and any position of trust and protection. Their loyalty and courage make them natural guardians.",
    love: "In relationships, 庚戌 individuals are devoted and protective partners. They take commitment very seriously and defend their loved ones fiercely. They need partners who appreciate their loyalty and share their values.",
    health: "Focus on lung and digestive health (Metal-Earth). The strong Earth supports good constitution. Regular vigorous exercise, stress management, and a high-fiber diet are recommended.",
    luckyColors: ["White", "Yellow", "Brown"],
    luckyNumbers: [7, 5, 8],
    compatibleAnimals: ["Tiger", "Rabbit", "Horse"],
    incompatibleAnimals: ["Dragon"],
  },
  "辛亥": {
    summary: "Xin Hai combines Yin Metal (the polished jade) with the Pig's Water. This is a reflective, intuitive combination — like a pearl resting at the bottom of the sea. Wisdom, depth, and hidden beauty.",
    personality: ["Deeply intuitive with a philosophical mind", "Gentle and compassionate toward all", "Artistic with a love for beauty in all forms", "Wise and reflective beyond their years"],
    career: "辛亥 people excel in contemplative and creative professions. They thrive in research, writing, spirituality, psychology, and the arts. Their depth of insight makes them exceptional philosophers, writers, and healers.",
    love: "In relationships, 辛亥 individuals are tender and spiritually connected partners. They seek deep soul-level connections. They need partners who appreciate their depth and give them space for reflection.",
    health: "Focus on respiratory and kidney health (Metal-Water). The reflective nature needs balance — avoid overthinking. Time in nature, creative expression, and gentle exercise support their wellbeing.",
    luckyColors: ["White", "Blue", "Black"],
    luckyNumbers: [6, 1, 4],
    compatibleAnimals: ["Goat", "Rabbit", "Tiger"],
    incompatibleAnimals: ["Snake"],
  },
  "壬子": {
    summary: "Ren Zi combines Yang Water (the vast ocean) with the Rat's Water. This is double Water — deep, powerful, and endlessly adaptive. Like the deep ocean — mysterious, potent, and full of hidden life.",
    personality: ["Deeply intuitive with almost psychic awareness", "Exceptionally adaptable in any situation", "Wise and philosophical with a global perspective", "Independent and self-sufficient"],
    career: "壬子 people are built for roles requiring depth and adaptability. They excel in research, psychology, spirituality, maritime careers, and any field involving water or deep analysis.",
    love: "In relationships, 壬子 individuals are deep and devoted partners. They seek profound emotional connections. They need partners who can navigate their emotional depth and respect their need for solitude.",
    health: "Focus on kidney health (double Water). The powerful Water element needs strong channels. Swimming, hydration, warm foods, and avoiding cold-damp environments support their health.",
    luckyColors: ["Blue", "Black", "Dark Green"],
    luckyNumbers: [1, 6, 10],
    compatibleAnimals: ["Ox", "Dragon", "Monkey"],
    incompatibleAnimals: ["Horse"],
  },
  "癸丑": {
    summary: "Gui Chou combines Yin Water (the gentle rain) with the Ox's Earth. This is a patient, nurturing combination — like spring rain on thawing soil. Persistence, growth, and quiet determination.",
    personality: ["Patient and persistent with quiet determination", "Nurturing and emotionally supportive", "Practical yet deeply intuitive", "Loyal and dependable in all relationships"],
    career: "癸丑 people excel in roles requiring patience and care. They thrive in education, healthcare, agriculture, environmental work, and traditional crafts. Their steady, nurturing approach makes them excellent mentors.",
    love: "In relationships, 癸丑 individuals are devoted and steadfast partners. They express love through consistent care and practical support. They seek lasting commitment and create stable, nurturing homes.",
    health: "Focus on kidney and digestive health (Water-Earth). Regular routines and moderate exercise suit their nature. Warm, nourishing foods and adequate rest support their wellbeing.",
    luckyColors: ["Blue", "Yellow", "Brown"],
    luckyNumbers: [2, 5, 8],
    compatibleAnimals: ["Snake", "Rooster", "Rat"],
    incompatibleAnimals: ["Goat"],
  },
  "甲寅": {
    summary: "Jia Yin combines Yang Wood (the towering tree) with the Tiger's Wood. This is double Wood — powerful, expansive, and fiercely independent. Like a great forest — strong, alive, and endlessly growing.",
    personality: ["Fiercely independent with a pioneer's spirit", "Natural leader with bold vision", "Generous and protective of their community", "Determined and unstoppable when pursuing goals"],
    career: "甲寅 people are natural pioneers and leaders. They thrive in entrepreneurship, environmental leadership, education, exploration, and any role that requires vision and courage.",
    love: "In relationships, 甲寅 individuals are passionate and protective partners. They bring strength and adventure to their relationships. They need partners who respect their independence and match their vitality.",
    health: "Focus on liver health (double Wood). This powerful Wood needs healthy expression through regular exercise and outdoor activity. Stretching, hiking, and avoiding liver-stressing substances are important.",
    luckyColors: ["Green", "Brown", "Blue"],
    luckyNumbers: [3, 8, 1],
    compatibleAnimals: ["Horse", "Dog", "Pig"],
    incompatibleAnimals: ["Monkey"],
  },
  "乙卯": {
    summary: "Yi Mao combines Yin Wood (the flowering vine) with the Rabbit's Wood. This is double Wood — graceful, artistic, and deeply intuitive. Like a flowering meadow in spring — beautiful, gentle, and alive.",
    personality: ["Exceptionally creative with refined artistic taste", "Gentle and diplomatic in all interactions", "Deeply intuitive and emotionally perceptive", "Graceful under pressure"],
    career: "乙卯 people are artists and creators at heart. They thrive in the arts, design, music, writing, counseling, and any field requiring creativity and sensitivity. Their refined sensibilities make them exceptional in creative leadership.",
    love: "In relationships, 乙卯 individuals are romantic and tender partners. They seek deep emotional and creative connections. They need partners who appreciate their artistic nature and provide emotional security.",
    health: "Focus on liver health (double Wood). Gentle exercise like tai chi, yoga, or dance suits their nature. Time in nature, creative expression, and a diet rich in greens support their health.",
    luckyColors: ["Green", "Pink", "Purple"],
    luckyNumbers: [2, 4, 8],
    compatibleAnimals: ["Goat", "Pig", "Dog"],
    incompatibleAnimals: ["Rooster"],
  },
  "丙辰": {
    summary: "Bing Chen combines Yang Fire (the blazing sun) with the Dragon's Earth. This is a dynamic, powerful combination — like a volcano awakening. Transformative energy, charisma, and world-changing potential.",
    personality: ["Charismatic and magnetically吸引人", "Transformative leader who inspires change", "Ambitious with grand visions", "Confident and boldly optimistic"],
    career: "丙辰 people are built for transformative leadership. They excel in politics, entertainment, entrepreneurship, technology innovation, and any role that allows them to make a significant impact.",
    love: "In relationships, 丙辰 individuals are passionate and devoted. They bring warmth and excitement to their partnerships. They need partners who share their vision and can handle their dynamic energy.",
    health: "Focus on heart and digestive health (Fire-Earth). The dynamic energy needs healthy outlets. Regular exercise, stress management, and a balanced diet are essential for maintaining health.",
    luckyColors: ["Red", "Yellow", "Gold"],
    luckyNumbers: [3, 5, 8],
    compatibleAnimals: ["Rat", "Monkey", "Rooster"],
    incompatibleAnimals: ["Dog"],
  },
  "丁巳": {
    summary: "Ding Si combines Yin Fire (the candle flame) with the Snake's Fire. This is double Fire — intense, refined, and deeply perceptive. Like a laser — focused, powerful, and capable of remarkable precision.",
    personality: ["Intensely focused with remarkable precision", "Deeply perceptive and intuitively brilliant", "Elegant and refined in expression", "Passionate with controlled, directed power"],
    career: "丁巳 people excel in roles requiring focus and insight. They thrive in research, technology, medicine, law, and the arts. Their ability to focus deeply makes them exceptional in specialized, high-precision fields.",
    love: "In relationships, 丁巳 individuals are intense and devoted. They seek profound emotional and intellectual connections. They need partners who respect their intensity and provide emotional warmth.",
    health: "Focus on heart health (double Fire). The intense Fire needs careful management. Cooling activities, meditation, and avoiding emotional extremes are critical for their health.",
    luckyColors: ["Red", "Purple", "Gold"],
    luckyNumbers: [6, 9, 2],
    compatibleAnimals: ["Ox", "Rooster", "Monkey"],
    incompatibleAnimals: ["Pig"],
  },
  "戊午": {
    summary: "Wu Wu combines Yang Earth (the great mountain) with the Horse's Fire. This is a warm, powerful combination — like a sun-baked mesa. Stability, passion, and generous warmth.",
    personality: ["Warm-hearted and generously supportive", "Confident leader with steady judgment", "Passionate yet grounded in practicality", "Loyal friend and devoted family member"],
    career: "Wu Wu people excel in roles combining leadership with service. They thrive in education, government, real estate, hospitality, and community leadership. Their warmth and stability make them natural community builders.",
    love: "In relationships, 戊午 individuals are passionate and devoted partners. They bring both excitement and stability to their relationships. They need partners who appreciate their warmth and share their values.",
    health: "Focus on heart and digestive health (Fire-Earth). The balanced elements support good constitution. Regular exercise, stress management, and a balanced diet maintain their health.",
    luckyColors: ["Yellow", "Red", "Brown"],
    luckyNumbers: [5, 7, 9],
    compatibleAnimals: ["Tiger", "Goat", "Dog"],
    incompatibleAnimals: ["Rat"],
  },
  "己未": {
    summary: "Ji Wei combines Yin Earth (the fertile soil) with the Goat's Earth. This is double Earth — deeply nurturing, stable, and abundant. Like a fertile valley — peaceful, prosperous, and life-giving.",
    personality: ["Deeply nurturing with a generous spirit", "Exceptionally dependable and trustworthy", "Creative with a gentle, artistic soul", "Patient and wise beyond measure"],
    career: "己未 people are natural nurturers and builders. They thrive in agriculture, real estate, education, healthcare, hospitality, and the arts. Their ability to create abundance and stability makes them exceptional in any field.",
    love: "In relationships, 己未 individuals are devoted and caring partners. They create deeply nurturing homes and invest everything in their relationships. They need partners who appreciate their generosity and provide emotional reciprocity.",
    health: "Focus on digestive health (double Earth). The strong Earth can lead to stagnation or dampness. Regular exercise, a varied diet, and staying active are essential for their wellbeing.",
    luckyColors: ["Yellow", "Brown", "Orange"],
    luckyNumbers: [5, 8, 2],
    compatibleAnimals: ["Rabbit", "Horse", "Pig"],
    incompatibleAnimals: ["Ox"],
  },
  "庚申": {
    summary: "Geng Shen combines Yang Metal (the raw ore) with the Monkey's Metal. This is double Metal — sharp, strong, and brilliantly incisive. Like a masterfully forged blade — precise, powerful, and resilient.",
    personality: ["Exceptionally sharp-minded and analytical", "Strong-willed with unwavering determination", "Independent and self-reliant to the core", "Natural leader with keen strategic instincts"],
    career: "庚申 people are built for excellence in demanding fields. They thrive in surgery, engineering, technology, finance, law, and military leadership. Their precision and determination drive them to the pinnacle of their profession.",
    love: "In relationships, 庚申 individuals are loyal and discerning. They have high standards but are deeply devoted once committed. They need partners who can match their intellect and respect their independence.",
    health: "Focus on lung health (double Metal). The strong Metal needs balance through moderate exercise and emotional expression. Breathing exercises, staying hydrated, and avoiding dryness are important.",
    luckyColors: ["White", "Gold", "Silver"],
    luckyNumbers: [7, 4, 9],
    compatibleAnimals: ["Rat", "Dragon", "Snake"],
    incompatibleAnimals: ["Tiger"],
  },
  "辛酉": {
    summary: "Xin You combines Yin Metal (the polished jade) with the Rooster's Metal. This is double Metal — refined, precise, and absolutely elegant. Like a perfect diamond — brilliant, hard, and flawless.",
    personality: ["Exquisite refinement with impeccable standards", "Precise and meticulous in every detail", "Elegant and poised in all situations", "Disciplined with an inner core of steel"],
    career: "辛酉 people are masters of precision and refinement. They excel in jewelry, luxury goods, editing, quality assurance, law, and the arts. Their exacting standards make them the best in their chosen field.",
    love: "In relationships, 辛酉 individuals are discerning and devoted. They have the highest standards but are deeply loyal once committed. They need partners who share their refinement and appreciate their precision.",
    health: "Focus on respiratory health (double Metal). The strong Metal needs gentle balance. Breathing exercises, adequate moisture, and emotional warmth help soften the hard Metal energy.",
    luckyColors: ["White", "Gold", "Silver"],
    luckyNumbers: [4, 6, 9],
    compatibleAnimals: ["Ox", "Snake", "Dragon"],
    incompatibleAnimals: ["Rabbit"],
  },
  "壬戌": {
    summary: "Ren Xu combines Yang Water (the vast ocean) with the Dog's Earth. This is a loyal, powerful combination — like a deep lake held by ancient dams. Emotional depth meets unwavering principles.",
    personality: ["Loyal and principled with deep emotional wisdom", "Powerful intuition combined with practical judgment", "Protective of loved ones and their values", "Independent yet deeply committed"],
    career: "壬戌 people excel in roles requiring both wisdom and integrity. They thrive in law, environmental leadership, philanthropy, psychology, and community organization. Their depth of character makes them natural leaders.",
    love: "In relationships, 壬戌 individuals are deeply devoted and protective. They seek profound emotional connections and lasting commitment. They need partners who share their values and appreciate their emotional depth.",
    health: "Focus on kidney and digestive health (Water-Earth). The interplay of elements needs balance. Regular exercise, stress management, and a warm, nourishing diet support their wellbeing.",
    luckyColors: ["Blue", "Yellow", "Brown"],
    luckyNumbers: [1, 5, 8],
    compatibleAnimals: ["Tiger", "Rabbit", "Horse"],
    incompatibleAnimals: ["Dragon"],
  },
  "癸亥": {
    summary: "Gui Hai combines Yin Water (the gentle rain) with the Pig's Water. This is double Water — the most intuitive, receptive combination in the calendar. Like a vast, peaceful lake reflecting the infinite sky.",
    personality: ["Deeply intuitive with profound spiritual awareness", "Exceptionally receptive and empathetically attuned", "Wise and philosophical with natural serenity", "Creative with a rich inner universe"],
    career: "癸亥 people are natural philosophers, healers, and artists. They thrive in spirituality, psychology, writing, the arts, and any field requiring deep insight. Their wisdom and creativity make them exceptional guides and creators.",
    love: "In relationships, 癸亥 individuals are deeply loving and spiritually connected. They seek soul-deep bonds and emotional authenticity. They need partners who honor their depth and provide gentle stability.",
    health: "Focus on kidney health (double Water). The powerful Water needs warmth and circulation. Warm foods, moderate exercise, time in sunlight, and avoiding cold-damp environments are essential.",
    luckyColors: ["Blue", "Black", "Dark Purple"],
    luckyNumbers: [1, 6, 10],
    compatibleAnimals: ["Goat", "Rabbit", "Tiger"],
    incompatibleAnimals: ["Snake"],
  },
};

const FAMOUS_BY_YEAR: Record<string, string[]> = {
  "甲子": ["Cristiano Ronaldo (1985)", "Albert Einstein (1879)", "Mark Zuckerberg (1984)"],
  "乙丑": ["Angelina Jolie (1975)", "Steve Jobs (1955)", "Barack Obama (1961)"],
  "丙寅": ["Leonardo DiCaprio (1974)", "Elon Musk (1971)", "Lionel Messi (1987)"],
  "丁卯": ["David Beckham (1975)", "Lady Gaga (1986)", "Keanu Reeves (1964)"],
  "戊辰": ["Jackie Chan (1954)", "Kanye West (1977)", "Miley Cyrus (1992)"],
  "己巳": ["Anne Hathaway (1982)", "Martin Luther King Jr. (1929)", "Taylor Swift (1989)"],
  "庚午": ["Audrey Hepburn (1929)", "Tom Cruise (1962)", "Jake Gyllenhaal (1980)"],
  "辛未": ["Scarlett Johansson (1984)", "Mike Tyson (1966)", "Ryan Reynolds (1976)"],
  "壬申": ["Elvis Presley (1935)", "Emma Watson (1990)", "Tom Hanks (1956)"],
  "癸酉": ["Keanu Reeves (1964)", "Natalie Portman (1981)", "Hugh Jackman (1968)"],
  "甲戌": ["Prince William (1982)", "Fidel Castro (1926)", "Julia Roberts (1967)"],
  "乙亥": ["Richard Branson (1950)", "Bill Clinton (1946)", "Paris Hilton (1981)"],
  "丙子": ["JFK Jr. (1960)", "Meryl Streep (1949)", "Beyoncé Knowles (1981)"],
  "丁丑": ["Shakira (1977)", "George Clooney (1961)", "Emma Roberts (1991)"],
  "戊寅": ["Bruce Lee (1940)", "Will Smith (1968)", "Johnny Depp (1963)"],
  "己卯": ["John Legend (1978)", "Kate Winslet (1975)", "Chanel Iman (1990)"],
  "庚辰": ["Georges St-Pierre (1981)", "Goldie Hawn (1945)", "Gong Li (1965)"],
  "辛巳": ["Mao Zedong (1893)", "Angelina Jolie (1975)", "Sandra Oh (1971)"],
  "壬午": ["Paul McCartney (1942)", "Madonna (1958)", "Halle Berry (1966)"],
  "癸未": ["Bill Gates (1955)", "Bruce Willis (1955)", "Emma Stone (1988)"],
  "甲申": ["Mark Twain (1835)", "Ludwig van Beethoven (1770)", "Walt Disney (1901)"],
  "乙酉": ["Heath Ledger (1979)", "Jude Law (1972)", "Naomi Campbell (1970)"],
  "丙戌": ["Donald Trump (1946)", "Steven Spielberg (1946)", "Chris Rock (1965)"],
  "丁亥": ["Michael Owen (1979)", "Fu Mingxia (1978)", "Jackson Rathbone (1984)"],
  "戊子": ["Michael Jackson (1958)", "Mao Zedong (1893)", "Linda Hamilton (1956)"],
  "己丑": ["Shigeru Miyamoto (1952)", "He Xiaopeng (1975)", "James Cameron (1954)"],
  "庚寅": ["Che Guevara (1928)", "Steve Martin (1945)", "Tom Hardy (1977)"],
  "辛卯": ["Denzel Washington (1954)", "Charles Darwin (1809)", "Kate Beckinsale (1973)"],
  "壬辰": ["Mao Zedong (1893)", "Angelina Jolie (1975)", "George Lucas (1944)"],
  "癸巳": ["Carrie Fisher (1956)", "Margaret Cho (1968)", "Benedict Cumberbatch (1976)"],
  "甲午": ["Jim Carrey (1962)", "Celine Dion (1968)", "Jennifer Lawrence (1990)"],
  "乙未": ["Albert Einstein (1879)", "Florence Nightingale (1820)", "Arnold Schwarzenegger (1947)"],
  "丙申": ["Kylie Jenner (1997)", "Frank Ocean (1987)", "Monica Bellucci (1964)"],
  "丁酉": ["Michael Bublé (1975)", "Jennifer Garner (1972)", "Owen Wilson (1968)"],
  "戊戌": ["Hillary Clinton (1947)", "John Legend (1978)", "Teddy Roosevelt (1858)"],
  "己亥": ["Justin Bieber (1994)", "President Xi Jinping (1953)", "Charles Leclerc (1997)"],
  "庚子": ["Donald Glover (1983)", "Bret Easton Ellis (1964)", "Pierre Curie (1859)"],
  "辛丑": ["Tom Cruise (1962)", "Princess Diana (1961)", "Rihanna (1988)"],
  "壬寅": ["Nicholas Cage (1964)", "John Mayer (1977)", "Benjamin Franklin (1706)"],
  "癸卯": ["David Bowie (1947)", "Quentin Tarantino (1963)", "Jared Leto (1971)"],
  "甲辰": ["Shahrukh Khan (1965)", "Jeff Bezos (1964)", "René Redzepi (1977)"],
  "乙巳": ["Margaret Cho (1968)", "Lenny Kravitz (1964)", "Anne Boleyn (1501)"],
  "丙午": ["Neil Armstrong (1930)", "Venus Williams (1980)", "KSI (1993)"],
  "丁未": ["Clive Owen (1964)", "Eva Mendes (1974)", "Rupert Grint (1988)"],
  "戊申": ["Megan Fox (1986)", "Robert Downey Jr. (1965)", "Jack Nicholson (1937)"],
  "己酉": ["Leonardo DiCaprio (1974)", "Britney Spears (1981)", "Christina Aguilera (1980)"],
  "庚戌": ["Angelina Jolie (1975)", "Pierce Brosnan (1953)", "Vladimir Putin (1952)"],
  "辛亥": ["Marcel Proust (1871)", "Katherine Hepburn (1907)", "James Marsden (1973)"],
  "壬子": ["Barack Obama (1961)", "Taylor Swift (1989)", "Kiefer Sutherland (1966)"],
  "癸丑": ["Amy Winehouse (1983)", "Jared Leto (1971)", "Vanessa Hudgens (1988)"],
  "甲寅": ["Jennifer Lopez (1969)", "Drew Barrymore (1975)", "Fidel Castro (1926)"],
  "乙卯": ["Missy Elliott (1971)", "Vince Vaughn (1970)", "Kelly Clarkson (1982)"],
  "丙辰": ["Donald Trump (1946)", "John Travolta (1954)", "Whoopi Goldberg (1955)"],
  "丁巳": ["Martin Scorsese (1942)", "Blake Lively (1987)", "Adolf Hitler (1889)"],
  "戊午": ["Ben Stiller (1965)", "Kylie Minogue (1968)", "Catherine Zeta-Jones (1969)"],
  "己未": ["Miles Davis (1926)", "Lily Collins (1989)", "Queen Elizabeth II (1926)"],
  "庚申": ["Mickey Rooney (1920)", "Eminem (1972)", "Ellen Pompeo (1969)"],
  "辛酉": ["Sarah Jessica Parker (1965)", "Gwyneth Paltrow (1972)", "Matt Damon (1970)"],
  "壬戌": ["Eleanor Roosevelt (1884)", "Owen Wilson (1968)", "Marc Anthony (1968)"],
  "癸亥": ["Prince Harry (1984)", "Liza Minnelli (1946)", "Benjamin Netanyahu (1949)"],
};

const STEM_BRANCH_INDEX = ["甲子","乙丑","丙寅","丁卯","戊辰","己巳","庚午","辛未","壬申","癸酉","甲戌","乙亥","丙子","丁丑","戊寅","己卯","庚辰","辛巳","壬午","癸未","甲申","乙酉","丙戌","丁亥","戊子","己丑","庚寅","辛卯","壬辰","癸巳","甲午","乙未","丙申","丁酉","戊戌","己亥","庚子","辛丑","壬寅","癸卯","甲辰","乙巳","丙午","丁未","戊申","己酉","庚戌","辛亥","壬子","癸丑","甲寅","乙卯","丙辰","丁巳","戊午","己未","庚申","辛酉","壬戌","癸亥"];

const ANIMAL_FROM_BRANCH: Record<string, string> = {
  "子": "rat", "丑": "ox", "寅": "tiger", "卯": "rabbit",
  "辰": "dragon", "巳": "snake", "午": "horse", "未": "goat",
  "申": "monkey", "酉": "rooster", "戌": "dog", "亥": "pig",
};

const ANIMAL_EN_FROM_BRANCH: Record<string, string> = {
  "子": "Rat", "丑": "Ox", "寅": "Tiger", "卯": "Rabbit",
  "辰": "Dragon", "巳": "Snake", "午": "Horse", "未": "Goat",
  "申": "Monkey", "酉": "Rooster", "戌": "Dog", "亥": "Pig",
};

const YIN_YANG: Record<string, "Yang" | "Yin"> = {
  "甲": "Yang", "乙": "Yin", "丙": "Yang", "丁": "Yin", "戊": "Yang",
  "己": "Yin", "庚": "Yang", "辛": "Yin", "壬": "Yang", "癸": "Yin",
};

const BRANCH_TO_ANIMAL_KEY: Record<string, string> = {
  "子": "rat", "丑": "ox", "寅": "tiger", "卯": "rabbit",
  "辰": "dragon", "巳": "snake", "午": "horse", "未": "goat",
  "申": "monkey", "酉": "rooster", "戌": "dog", "亥": "pig",
};

/** Get the stem-branch pair (Chinese) for a given year */
function getStemBranch(year: number): { stem: string; branch: string; index: number } {
  const idx = ((year - 4) % 60 + 60) % 60;
  const pair = STEM_BRANCH_INDEX[idx];
  const stem = HEAVENLY_STEMS[STEM_BRANCH_INDEX.indexOf(pair) % 10];
  const branch = EARTHLY_BRANCHES[STEM_BRANCH_INDEX.indexOf(pair) % 12];
  return { stem, branch, index: idx };
}

/** Get the stem index from the stem character */
function getStemIndex(stem: string): number {
  return HEAVENLY_STEMS.indexOf(stem);
}

/** Get the branch index from the branch character */
function getBranchIndex(branch: string): number {
  return EARTHLY_BRANCHES.indexOf(branch);
}

export function getBirthYearContent(year: number): BirthYearInfo | null {
  if (year < 1900 || year > 2050) return null;

  const { stem, branch, index } = getStemBranch(year);
  const stemBranch = stem + branch;
  const stemIndex = getStemIndex(stem);
  const branchIndex = getBranchIndex(branch);
  const stemEn = HEAVENLY_STEMS_EN[stemIndex];
  const branchEn = EARTHLY_BRANCHES_EN[branchIndex];
  const animalKey = ANIMAL_FROM_BRANCH[branch];
  const animal = ANIMAL_EN_FROM_BRANCH[branch];
  const element = STEM_WUXING[stem];
  const yinYang = YIN_YANG[stem];
  const baseContent = YEAR_CONTENT[stemBranch];
  const famous = FAMOUS_BY_YEAR[stemBranch] || [];

  if (!baseContent) return null;

  return {
    year,
    stem,
    stemEn,
    branch,
    branchEn,
    stemBranch,
    stemBranchEn: `${stemEn} ${branchEn}`,
    animal,
    animalKey,
    element,
    yinYang,
    content: {
      ...baseContent,
      famous,
    },
  };
}

export function getYearRange(start: number, end: number): BirthYearInfo[] {
  const years: BirthYearInfo[] = [];
  for (let y = start; y <= end; y++) {
    const info = getBirthYearContent(y);
    if (info) years.push(info);
  }
  return years;
}

/** All years from 1900 to 2031 */
export const ALL_BIRTH_YEARS = getYearRange(1900, 2031);

export const BIRTH_YEAR_START = 1900;
export const BIRTH_YEAR_END = 2031;
