import { EARTHLY_BRANCHES, EARTHLY_BRANCHES_EN, BRANCH_WUXING } from "./constants";

export interface BranchDetail {
  chinese: string;
  pinyin: string;
  element: string;
  zodiacAnimal: string;
  zodiacKey: string;
  season: string;
  direction: string;
  time: string;
  month: string;
  hiddenStems: string[];
  personality: string;
  strengths: string[];
  weaknesses: string[];
  career: string;
  relationships: string;
  health: string;
  compatibleBranches: string[];
  description: string;
  imageWords: string;
}

const BRANCHES_DATA: Record<string, BranchDetail> = {
  "子": {
    chinese: "子",
    pinyin: "Zi",
    element: "Water",
    zodiacAnimal: "Rat",
    zodiacKey: "rat",
    season: "Winter",
    direction: "North",
    time: "11 PM – 1 AM",
    month: "December",
    hiddenStems: ["癸"],
    personality: "Zi is the energy of midnight and deep winter — still, potent, and full of hidden potential. People with strong Zi energy are sharp-witted, resourceful, and highly adaptable. Like the rat, they are survivors who can navigate any environment with intelligence and charm.",
    strengths: ["Quick-witted and intelligent", "Highly adaptable and resourceful", "Charming and socially skilled", "Strong intuition and survival instincts"],
    weaknesses: ["Can be opportunistic or cunning", "Tendency to be restless", "May be overly ambitious", "Difficulty trusting others"],
    career: "Zi people excel in careers requiring intelligence and adaptability. They thrive in writing, analysis, entrepreneurship, sales, and any field where quick thinking is rewarded. Their resourcefulness makes them excellent in dynamic, fast-paced environments.",
    relationships: "In relationships, Zi is charming and attentive. They are romantic partners who value intellectual stimulation and emotional connection. They need partners who appreciate their social nature and can match their mental agility.",
    health: "Zi energy governs the kidneys, bladder, and adrenal system. As a Water branch, warmth and hydration are essential. People with strong Zi influence benefit from adequate rest, warm foods, and practices that calm the nervous system.",
    compatibleBranches: ["丑", "辰", "申"],
    description: "Zi (子) is the first Earthly Branch, associated with the Rat and the Water element. It represents midnight, deep winter, and the height of Yin energy. Zi is the most intelligent and adaptable of the branches, carrying the energy of potential — like a seed waiting beneath frozen soil.",
    imageWords: "Midnight stillness, hidden potential, sharp intelligence, adaptability, winter's secret abundance",
  },
  "丑": {
    chinese: "丑",
    pinyin: "Chou",
    element: "Earth",
    zodiacAnimal: "Ox",
    zodiacKey: "ox",
    season: "Winter",
    direction: "NNE",
    time: "1 AM – 3 AM",
    month: "January",
    hiddenStems: ["己", "癸", "辛"],
    personality: "Chou is the energy of the deep winter night — cold outside but already preparing for spring. People with strong Chou energy are steadfast, diligent, and incredibly patient. Like the ox, they work tirelessly and carry heavy burdens without complaint.",
    strengths: ["Diligent and hardworking", "Patient and persistent", "Reliable and trustworthy", "Strong sense of responsibility"],
    weaknesses: ["Stubborn and resistant to change", "Can be overly conservative", "May be pessimistic", "Difficulty expressing emotions"],
    career: "Chou people excel in roles requiring persistence and reliability. They thrive in agriculture, real estate, engineering, finance, and traditional crafts. Their steady, methodical approach makes them invaluable in any organization that values consistency.",
    relationships: "In relationships, Chou is loyal and devoted. They may be slow to open up, but once committed, they are steadfast partners. They express love through actions rather than words and value long-term commitment above all.",
    health: "Chou energy governs the spleen, stomach, and digestive system. As an Earth branch, regular routines and balanced meals are essential. People with strong Chou influence should watch for stagnation and ensure regular physical activity.",
    compatibleBranches: ["子", "巳", "酉"],
    description: "Chou (丑) is the second Earthly Branch, associated with the Ox and the Earth element. It represents the deepest part of winter (January), when the cold is most intense but the first stirrings of spring are already present. Chou is the most determined and reliable of the branches.",
    imageWords: "Frozen earth, patient strength, diligent labor, hidden preparation, unshakeable reliability",
  },
  "寅": {
    chinese: "寅",
    pinyin: "Yin",
    element: "Wood",
    zodiacAnimal: "Tiger",
    zodiacKey: "tiger",
    season: "Spring",
    direction: "ENE",
    time: "3 AM – 5 AM",
    month: "February",
    hiddenStems: ["甲", "丙", "戊"],
    personality: "Yin is the energy of dawn and early spring — explosive, exciting, and full of possibilities. People with strong Yin energy are courageous, confident, and naturally commanding. Like the tiger, they are born leaders who charge ahead without fear.",
    strengths: ["Courage and boldness", "Natural leadership and charisma", "Passion and enthusiasm", "Generosity and protectiveness"],
    weaknesses: ["Impulsive and reckless", "Can be hot-tempered", "Restless and impatient", "May be rebellious against authority"],
    career: "Yin people thrive in leadership and pioneering roles. They excel in entrepreneurship, management, entertainment, sports, and any field that rewards bold action. Their ability to inspire others makes them exceptional team leaders and motivators.",
    relationships: "In relationships, Yin is passionate and protective. They bring excitement and intensity to their partnerships. They need partners who respect their independence and can match their energy and enthusiasm.",
    health: "Yin energy governs the liver, gallbladder, and tendons. As a Wood branch, regular exercise and stretching are important. People with strong Yin influence need to manage their intensity to avoid burnout and liver stress.",
    compatibleBranches: ["午", "戌", "亥"],
    description: "Yin (寅) is the third Earthly Branch, associated with the Tiger and the Wood element. It represents dawn and the beginning of spring — the explosive energy of new life breaking through the soil. Yin is the most courageous and dynamic of all the branches.",
    imageWords: "Dawn's explosion, tiger's courage, spring's first breath, dynamic leadership, fearless initiative",
  },
  "卯": {
    chinese: "卯",
    pinyin: "Mao",
    element: "Wood",
    zodiacAnimal: "Rabbit",
    zodiacKey: "rabbit",
    season: "Spring",
    direction: "East",
    time: "5 AM – 7 AM",
    month: "March",
    hiddenStems: ["乙"],
    personality: "Mao is the energy of sunrise and spring equinox — perfectly balanced, gentle, and harmonious. People with strong Mao energy are graceful, diplomatic, and artistically sensitive. Like the rabbit, they move through life with elegance and caution, creating beauty wherever they go.",
    strengths: ["Diplomacy and social grace", "Artistic talent and creativity", "Gentleness and compassion", "Excellent judgment and caution"],
    weaknesses: ["Overly cautious and indecisive", "Can be superficial or evasive", "May avoid conflict at all costs", "Tendency to be reserved"],
    career: "Mao people excel in creative and diplomatic professions. They thrive in the arts, design, counseling, diplomacy, law, and any field requiring refined judgment. Their ability to create harmony makes them excellent in team-oriented environments.",
    relationships: "In relationships, Mao is gentle and romantic. They seek peace and harmony above all and are skilled at creating beautiful, comfortable homes. They need partners who appreciate their sensitivity and provide emotional stability.",
    health: "Mao energy governs the liver and eyes. As a Yin Wood branch, gentle exercise like tai chi, yoga, and stretching are ideal. People with strong Mao influence benefit from a calm environment and a diet rich in leafy greens.",
    compatibleBranches: ["未", "亥", "戌"],
    description: "Mao (卯) is the fourth Earthly Branch, associated with the Rabbit and the Wood element. It represents sunrise and the spring equinox — the point of perfect balance between Yin and Yang. Mao is the most graceful and diplomatic of all the branches.",
    imageWords: "Sunrise balance, rabbit's grace, spring equinox, gentle harmony, diplomatic refinement",
  },
  "辰": {
    chinese: "辰",
    pinyin: "Chen",
    element: "Earth",
    zodiacAnimal: "Dragon",
    zodiacKey: "dragon",
    season: "Spring",
    direction: "ESE",
    time: "7 AM – 9 AM",
    month: "April",
    hiddenStems: ["戊", "乙", "癸"],
    personality: "Chen is the energy of late spring — full of growth, vitality, and dramatic transformation. People with strong Chen energy are powerful, charismatic, and endlessly ambitious. Like the dragon, they command attention and possess an almost magical ability to bring their visions to life.",
    strengths: ["Charisma and commanding presence", "Ambition and vision", "Transformative power", "Confidence and optimism"],
    weaknesses: ["Can be arrogant or domineering", "Impatient with slower people", "May be overly demanding", "Difficulty accepting criticism"],
    career: "Chen people are built for leadership and impact. They excel in executive roles, entertainment, politics, technology, and any field where they can shape the future. Their vision and charisma make them natural CEOs, founders, and industry leaders.",
    relationships: "In relationships, Chen is passionate and romantic. They bring excitement and grand visions to their partnerships. They need partners who can match their ambition and appreciate their dramatic, generous nature.",
    health: "Chen energy governs the spleen, stomach, and digestive system. As an Earth branch with Wood and Water hidden, the energy is complex. People with strong Chen influence benefit from regular routines, stress management, and moderate exercise.",
    compatibleBranches: ["子", "申", "酉"],
    description: "Chen (辰) is the fifth Earthly Branch, associated with the Dragon and the Earth element. It represents late spring (April), when the energy of growth reaches its peak before transforming into summer. Chen is the most powerful and transformative of all the branches.",
    imageWords: "Dragon's awakening, peak spring, transformative power, magnanimous authority, visionary fire",
  },
  "巳": {
    chinese: "巳",
    pinyin: "Si",
    element: "Fire",
    zodiacAnimal: "Snake",
    zodiacKey: "snake",
    season: "Summer",
    direction: "SSE",
    time: "9 AM – 11 AM",
    month: "May",
    hiddenStems: ["丙", "庚", "戊"],
    personality: "Si is the energy of late spring to early summer — rising, intense, and full of hidden knowledge. People with strong Si energy are wise, mysterious, and deeply strategic. Like the snake, they are elegant, perceptive, and carry a quiet power that others can sense.",
    strengths: ["Wisdom and strategic thinking", "Intuition and perceptiveness", "Elegance and poise", "Deep focus and determination"],
    weaknesses: ["Can be secretive and guarded", "Tendency toward jealousy", "May be possessive", "Difficulty trusting others"],
    career: "Si people excel in roles requiring strategy and depth. They thrive in research, finance, law, philosophy, consulting, and any field where deep thinking is valued. Their strategic minds make them exceptional advisors, analysts, and planners.",
    relationships: "In relationships, Si is passionate and deeply committed. They seek profound emotional and intellectual connections. They need partners who respect their depth and give them space for reflection while providing loyalty.",
    health: "Si energy governs the heart, blood, and circulation. As a Fire branch with hidden Metal and Earth, the energy is complex. People with strong Si influence need to manage stress and avoid emotional extremes.",
    compatibleBranches: ["丑", "酉", "申"],
    description: "Si (巳) is the sixth Earthly Branch, associated with the Snake and the Fire element. It represents late spring to early summer (May), when the rising Yang energy becomes intense. Si is the most wise and mysterious of all the branches.",
    imageWords: "Sunlit wisdom, serpent's knowing, rising intensity, strategic depth, elegant mystery",
  },
  "午": {
    chinese: "午",
    pinyin: "Wu",
    element: "Fire",
    zodiacAnimal: "Horse",
    zodiacKey: "horse",
    season: "Summer",
    direction: "South",
    time: "11 AM – 1 PM",
    month: "June",
    hiddenStems: ["丁", "己"],
    personality: "Wu is the energy of noon and summer solstice — the peak of Yang energy, hot, bright, and unrestrained. People with strong Wu energy are passionate, independent, and endlessly energetic. Like the horse, they love freedom and hate being confined.",
    strengths: ["Passion and enthusiasm", "Independence and self-reliance", "Social charm and magnetism", "Adventurous spirit"],
    weaknesses: ["Impulsive and restless", "Can be self-centered", "Impatient with routine", "May overextend themselves"],
    career: "Wu people thrive in dynamic, high-energy environments. They excel in sales, entertainment, travel, sports, entrepreneurship, and any field that rewards passion and independent thinking. Their energy inspires others and drives results.",
    relationships: "In relationships, Wu is passionate and exciting. They bring adventure and spontaneity to their partnerships. They need partners who respect their need for freedom and can keep up with their energetic lifestyle.",
    health: "Wu energy governs the heart, blood vessels, and complexion. As the peak of Yang Fire, people with strong Wu influence need to manage their energy to avoid burnout. Cooling activities, rest, and a calm environment are essential.",
    compatibleBranches: ["寅", "未", "戌"],
    description: "Wu (午) is the seventh Earthly Branch, associated with the Horse and the Fire element. It represents noon and the summer solstice — the apex of Yang energy in the day and the year. Wu is the most passionate and自由 of all the branches.",
    imageWords: "Noonday sun, summer peak, untamed passion, horse's freedom, blazing vitality",
  },
  "未": {
    chinese: "未",
    pinyin: "Wei",
    element: "Earth",
    zodiacAnimal: "Goat",
    zodiacKey: "goat",
    season: "Summer",
    direction: "SSW",
    time: "1 PM – 3 PM",
    month: "July",
    hiddenStems: ["己", "丁", "乙"],
    personality: "Wei is the energy of early afternoon and late summer — abundant, gentle, and reflective. People with strong Wei energy are creative, compassionate, and artistically gifted. Like the goat, they are gentle souls who appreciate beauty and comfort.",
    strengths: ["Creativity and artistic talent", "Compassion and empathy", "Gentleness and patience", "Adaptability in social situations"],
    weaknesses: ["Can be indecisive and hesitant", "Tendency to worry", "May be overly dependent", "Difficulty with criticism"],
    career: "Wei people excel in creative and helping professions. They thrive in the arts, design, counseling, education, healthcare, and any field where creativity meets compassion. Their ability to connect with others makes them beloved colleagues.",
    relationships: "In relationships, Wei is tender and devoted. They create warm, beautiful homes and invest deeply in their relationships. They need partners who appreciate their sensitivity and provide emotional stability.",
    health: "Wei energy governs the spleen, stomach, and digestive system. As an Earth branch with hidden Fire and Wood, the energy is nurturing but complex. People with strong Wei influence benefit from regular routines and creative expression.",
    compatibleBranches: ["卯", "午", "亥"],
    description: "Wei (未) is the eighth Earthly Branch, associated with the Goat and the Earth element. It represents early afternoon and late summer (July), when the abundance of summer begins to turn toward harvest. Wei is the most creative and gentle of all the branches.",
    imageWords: "Summer's abundance, gentle creativity, pastoral peace, artistic soul, nurturing warmth",
  },
  "申": {
    chinese: "申",
    pinyin: "Shen",
    element: "Metal",
    zodiacAnimal: "Monkey",
    zodiacKey: "monkey",
    season: "Autumn",
    direction: "WSW",
    time: "3 PM – 5 PM",
    month: "August",
    hiddenStems: ["庚", "壬", "戊"],
    personality: "Shen is the energy of late afternoon and early autumn — the energy begins to contract, sharpening the mind. People with strong Shen energy are brilliant, innovative, and endlessly entertaining. Like the monkey, they are curious, clever, and always one step ahead.",
    strengths: ["Brilliance and innovative thinking", "Quick wit and adaptability", "Versatility and resourcefulness", "Charm and humor"],
    weaknesses: ["Can be mischievous or manipulative", "Restless and easily bored", "May be arrogant", "Difficulty committing to one path"],
    career: "Shen people thrive in roles requiring intelligence and innovation. They excel in technology, finance, media, research, and entrepreneurship. Their quick minds and adaptability make them natural innovators and problem-solvers.",
    relationships: "In relationships, Shen is charming and stimulating. They keep relationships exciting with their wit and creativity. They need partners who can match their mental agility and appreciate their playful nature.",
    health: "Shen energy governs the lungs, large intestine, and skin. As a Metal branch, respiratory health is important. People with strong Shen influence benefit from breathing exercises, clean air, and practices that promote focus.",
    compatibleBranches: ["子", "辰", "巳"],
    description: "Shen (申) is the ninth Earthly Branch, associated with the Monkey and the Metal element. It represents late afternoon and early autumn (August), when the expansive Yang energy begins to contract inward. Shen is the most brilliant and innovative of all the branches.",
    imageWords: "Monkey's genius, autumn sharpness, inventive spark, playful brilliance, contracted power",
  },
  "酉": {
    chinese: "酉",
    pinyin: "You",
    element: "Metal",
    zodiacAnimal: "Rooster",
    zodiacKey: "rooster",
    season: "Autumn",
    direction: "West",
    time: "5 PM – 7 PM",
    month: "September",
    hiddenStems: ["辛"],
    personality: "You is the energy of sunset and autumn equinox — balanced but leaning inward, the time of harvest and judgment. People with strong You energy are precise, disciplined, and impeccably honest. Like the rooster, they are punctual, proud, and not afraid to speak their minds.",
    strengths: ["Precision and attention to detail", "Discipline and strong work ethic", "Honesty and integrity", "Organization and efficiency"],
    weaknesses: ["Can be overly critical", "Perfectionist tendencies", "May be blunt or harsh", "Difficulty relaxing"],
    career: "You people excel in roles requiring precision and organization. They thrive in management, journalism, medicine, law, finance, and any field where accuracy is paramount. Their high standards make them exceptional in quality-focused roles.",
    relationships: "In relationships, You is loyal and devoted. They may be critical at times, but their intentions come from a place of care. They need partners who appreciate their honesty and share their values of integrity and order.",
    health: "You energy governs the lungs and respiratory system. As a pure Yin Metal branch, respiratory health is paramount. People with strong You influence benefit from breathing exercises, a clean environment, and practices that help them relax.",
    compatibleBranches: ["丑", "巳", "辰"],
    description: "You (酉) is the tenth Earthly Branch, associated with the Rooster and the Metal element. It represents sunset and the autumn equinox (September) — the point of balance when Yang begins to yield to Yin. You is the most precise and disciplined of all the branches.",
    imageWords: "Sunset precision, rooster's call, autumn harvest, disciplined refinement, crystalline clarity",
  },
  "戌": {
    chinese: "戌",
    pinyin: "Xu",
    element: "Earth",
    zodiacAnimal: "Dog",
    zodiacKey: "dog",
    season: "Autumn",
    direction: "WNW",
    time: "7 PM – 9 PM",
    month: "October",
    hiddenStems: ["戊", "辛", "丁"],
    personality: "Xu is the energy of evening and late autumn — the energy is sinking, preparing for the stillness of winter. People with strong Xu energy are loyal, principled, and protective. Like the dog, they stand guard over what matters most and are fiercely devoted to their people.",
    strengths: ["Loyalty and devotion", "Strong sense of justice", "Protective and caring nature", "Reliability and trustworthiness"],
    weaknesses: ["Can be anxious or pessimistic", "Stubborn in their views", "May be too serious", "Difficulty with change"],
    career: "Xu people excel in roles requiring loyalty and integrity. They thrive in law, military, social work, security, and any position of trust. Their commitment to justice makes them powerful advocates and protectors.",
    relationships: "In relationships, Xu is faithful and devoted. They take commitment very seriously and protect their loved ones fiercely. They need partners who appreciate their loyalty and share their values of honesty and integrity.",
    health: "Xu energy governs the spleen, stomach, and digestive system. As an Earth branch with hidden Metal and Fire, the energy is protective but can lead to worry. People with strong Xu influence benefit from stress management and regular exercise.",
    compatibleBranches: ["寅", "卯", "午"],
    description: "Xu (戌) is the eleventh Earthly Branch, associated with the Dog and the Earth element. It represents evening and late autumn (October), when the Yang energy recedes and the world prepares for winter's rest. Xu is the most loyal and principled of all the branches.",
    imageWords: "Dog's vigil, autumn dusk, principled protection, loyal guardianship, gathering stillness",
  },
  "亥": {
    chinese: "亥",
    pinyin: "Hai",
    element: "Water",
    zodiacAnimal: "Pig",
    zodiacKey: "pig",
    season: "Winter",
    direction: "NNW",
    time: "9 PM – 11 PM",
    month: "November",
    hiddenStems: ["壬", "甲"],
    personality: "Hai is the energy of late evening and early winter — the energy is deep, receptive, and rich with inner wisdom. People with strong Hai energy are generous, intuitive, and deeply spiritual. Like the pig, they enjoy life's pleasures and share their abundance freely.",
    strengths: ["Generosity and open-heartedness", "Deep intuition and spiritual connection", "Patience and contentment", "Creativity and imagination"],
    weaknesses: ["Can be naive or overly trusting", "Tendency to overindulge", "May be materialistic", "Difficulty with confrontation"],
    career: "Hai people excel in roles that combine creativity with generosity. They thrive in the arts, philanthropy, hospitality, spiritual guidance, and any field where they can bring beauty and abundance to others.",
    relationships: "In relationships, Hai is devoted and affectionate. They give generously of their time, resources, and love. They need partners who appreciate their generous nature and provide the emotional grounding they need.",
    health: "Hai energy governs the kidneys, bladder, and reproductive system. As a Water branch with hidden Wood, the energy flows deep. People with strong Hai influence benefit from warmth, adequate rest, and activities that ground them.",
    compatibleBranches: ["寅", "卯", "未"],
    description: "Hai (亥) is the twelfth Earthly Branch, associated with the Pig and the Water element. It represents late evening and early winter (November), when Yin energy is at its height and the world turns inward. Hai is the most generous and intuitive of all the branches.",
    imageWords: "Winter's depth, pig's abundance, generous spirit, intuitive wisdom, receptive stillness",
  },
};

export function getBranchDetail(slug: string): BranchDetail | null {
  const entry = Object.entries(BRANCHES_DATA).find(
    ([chinese, data]) => chinese === slug || data.pinyin.toLowerCase() === slug.toLowerCase() || data.zodiacKey === slug.toLowerCase()
  );
  return entry ? entry[1] : null;
}

export const ALL_BRANCHES = Object.values(BRANCHES_DATA);

export const BRANCH_SLUGS = EARTHLY_BRANCHES_EN.map((en) => en.toLowerCase());
export const BRANCH_CHINESE = EARTHLY_BRANCHES;
