export const FIVE_ELEMENTS = [
  {
    key: "wood",
    name: "Wood",
    chinese: "木 (Mù)",
    season: "Spring",
    direction: "East",
    color: "Green",
    shape: "Rectangle / Column",
    planet: "Jupiter",
    climate: "Windy",
    sound: "Shout",
    number: 3,
    emotion: "Anger → Kindness",
    personality: "Creative, expansive, generous, idealistic",
    strength: "Strong vision, growth-oriented, nurturing leader",
    weakness: "Impulsive, easily frustrated, can be rigid",
    career: "Education, arts, design, gardening, writing, coaching",
    health: "Liver, eyes, tendons, gallbladder",
    description: "Wood is the element of spring and new beginnings. Like a tree reaching toward the sun, Wood energy is about growth, expansion, and pushing forward. People with strong Wood energy are natural visionaries — they see the big picture and inspire others to grow. Wood needs balance: too much leads to rigidity and impatience; too little leads to lack of direction.",
    dailyTips: [
      "Stretch and move your body to keep Wood energy flowing",
      "Add green plants to your workspace",
      "Practice patience when things don't go as planned",
      "Take breaks in nature to recharge",
      "Write down your long-term vision and revisit it weekly",
    ],
    compatibleElements: ["Water", "Fire"],
    challengingElements: ["Metal"],
  },
  {
    key: "fire",
    name: "Fire",
    chinese: "火 (Huǒ)",
    season: "Summer",
    direction: "South",
    color: "Red",
    shape: "Triangle / Pointed",
    planet: "Mars",
    climate: "Hot",
    sound: "Laugh",
    number: 9,
    emotion: "Joy → Over-excitement",
    personality: "Passionate, charismatic, dynamic, expressive",
    strength: "Natural leader, magnetic presence, inspires others",
    weakness: "Can burn out, impatient, temperamental",
    career: "Entertainment, sales, leadership, sports, performing arts",
    health: "Heart, blood vessels, tongue, complexion",
    description: "Fire is the element of summer, passion, and transformation. It represents warmth, illumination, and the spark of life itself. Fire people are natural-born leaders who light up every room they enter. They thrive on excitement and are driven by their hearts. But like a real flame, Fire needs fuel and control — too strong and it consumes everything; too weak and it extinguishes.",
    dailyTips: [
      "Cool down with meditation or quiet time",
      "Wear red or vibrant colors when you need confidence",
      "Avoid overheating — take breaks in shaded areas",
      "Channel passion into creative projects",
      "Practice deep breathing to calm internal fire",
    ],
    compatibleElements: ["Wood", "Earth"],
    challengingElements: ["Water"],
  },
  {
    key: "earth",
    name: "Earth",
    chinese: "土 (Tǔ)",
    season: "Late Summer / Transition",
    direction: "Center",
    color: "Yellow / Brown",
    shape: "Square / Flat",
    planet: "Saturn",
    climate: "Damp",
    sound: "Sing",
    number: 5,
    emotion: "Empathy → Worry",
    personality: "Stable, nurturing, practical, dependable",
    strength: "Reliable, grounded, excellent mediator, patient",
    weakness: "Can be stubborn, resistant to change, overprotective",
    career: "Real estate, agriculture, hospitality, counseling, healthcare",
    health: "Spleen, stomach, muscles, mouth",
    description: "Earth is the element of stability, nourishment, and the center. Just as the earth supports all life, Earth energy provides the foundation for everything else. Earth people are the rock of their communities — dependable, nurturing, and always there when needed. They think in terms of sustainability and long-term security. Earth energy is about coming home to yourself.",
    dailyTips: [
      "Spend time gardening or walking barefoot on grass",
      "Create a stable daily routine",
      "Wear earth tones (yellow, brown, beige) for grounding",
      "Practice letting go of worry through journaling",
      "Cook and share a meal with loved ones",
    ],
    compatibleElements: ["Fire", "Metal"],
    challengingElements: ["Wood"],
  },
  {
    key: "metal",
    name: "Metal",
    chinese: "金 (Jīn)",
    season: "Autumn",
    direction: "West",
    color: "White / Gold",
    shape: "Round / Circular",
    planet: "Venus",
    climate: "Dry",
    sound: "Weep",
    number: 4,
    emotion: "Grief → Courage",
    personality: "Disciplined, precise, determined, structured",
    strength: "Strong will, organized, high standards, integrity",
    weakness: "Can be rigid, critical, emotionally distant",
    career: "Finance, law, engineering, military, surgery, technology",
    health: "Lungs, skin, large intestine, nose",
    description: "Metal is the element of autumn, structure, and refinement. Like ore that is forged into steel, Metal energy is about discipline, precision, and inner strength. Metal people have an innate sense of justice and order. They set high standards — for themselves and others — and have the determination to meet them. Metal energy governs boundaries, both physical and emotional.",
    dailyTips: [
      "Declutter your space to let Metal energy flow",
      "Practice deep breathing exercises for lung health",
      "Wear white, gold, or silver to enhance Metal energy",
      "Set clear boundaries in relationships",
      "Take time for reflection and letting go",
    ],
    compatibleElements: ["Earth", "Water"],
    challengingElements: ["Fire"],
  },
  {
    key: "water",
    name: "Water",
    chinese: "水 (Shuǐ)",
    season: "Winter",
    direction: "North",
    color: "Blue / Black",
    shape: "Curved / Wavy",
    planet: "Mercury",
    climate: "Cold",
    sound: "Groan",
    number: 1,
    emotion: "Fear → Calm",
    personality: "Adaptable, intuitive, reflective, wise",
    strength: "Deep wisdom, emotional intelligence, adaptability",
    weakness: "Can be overly sensitive, indecisive, secretive",
    career: "Research, psychology, spirituality, art, marine work",
    health: "Kidneys, bladder, bones, ears",
    description: "Water is the element of winter, wisdom, and flow. Water is the softest substance yet can carve through rock over time. Water people are deeply intuitive and emotionally intelligent. They adapt to any situation, flowing around obstacles rather than confronting them head-on. Water energy represents the deep, unconscious mind and the wellspring of inner wisdom.",
    dailyTips: [
      "Drink plenty of water and stay hydrated",
      "Spend time near water — rivers, lakes, or the ocean",
      "Practice meditation to connect with your inner wisdom",
      "Wear blue or black to strengthen Water energy",
      "Keep a dream journal to tap into your intuition",
    ],
    compatibleElements: ["Metal", "Wood"],
    challengingElements: ["Earth"],
  },
];
