import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for The Ba Zi (thebazi.com). Please read these terms carefully before using our services.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:py-16">
      <h1 className="text-3xl font-bold tracking-tight sm:text-4xl mb-2">Terms of Service</h1>
      <p className="text-sm text-zinc-500 mb-8">Last updated: May 25, 2026</p>

      <div className="prose prose-zinc prose-sm max-w-none space-y-6">
        <h2 className="text-lg font-semibold">1. Acceptance of Terms</h2>
        <p>
          By accessing or using The Ba Zi (thebazi.com), you agree to be bound by these Terms of Service.
          If you do not agree with any part of these terms, you may not use our services.
        </p>

        <h2 className="text-lg font-semibold">2. Service Description</h2>
        <p>
          The Ba Zi provides automated Ba Zi (Four Pillars of Destiny) calculations and AI-generated
          interpretations based on traditional Chinese metaphysical principles. Our services are:
        </p>
        <ul>
          <li>Provided for <strong>entertainment, educational, and self-reflection purposes only</strong></li>
          <li>Not a substitute for professional advice (financial, medical, legal, or psychological)</li>
          <li>Generated by automated calculations and AI — not by human fortune tellers</li>
        </ul>

        <h2 className="text-lg font-semibold">3. Disclaimer — For Entertainment Purposes</h2>
        <p>
          <strong>IMPORTANT:</strong> All readings, predictions, and interpretations provided by The Ba Zi
          are for entertainment and informational purposes only. You should not:
        </p>
        <ul>
          <li>Make financial decisions based on your Ba Zi reading</li>
          <li>Delay or avoid seeking professional medical or mental health care</li>
          <li>Make legal decisions based on astrological predictions</li>
          <li>Use readings as a substitute for professional advice of any kind</li>
        </ul>

        <h2 className="text-lg font-semibold">4. User Responsibilities</h2>
        <p>You agree to:</p>
        <ul>
          <li>Provide accurate birth information (you may use approximate data if unsure)</li>
          <li>Not use the service for any unlawful purpose</li>
          <li>Not attempt to reverse-engineer, scrape, or abuse our systems</li>
          <li>Not rely on readings for critical life decisions</li>
        </ul>

        <h2 className="text-lg font-semibold">5. Intellectual Property</h2>
        <p>
          All content on The Ba Zi, including text, graphics, calculations, and AI-generated readings,
          is the property of The Ba Zi unless otherwise stated. You may not reproduce, distribute,
          or create derivative works without our permission.
        </p>

        <h2 className="text-lg font-semibold">6. Limitation of Liability</h2>
        <p>
          The Ba Zi and its operators shall not be liable for any direct, indirect, incidental,
          consequential, or punitive damages arising from your use of or reliance on our service.
          Ba Zi readings are provided &ldquo;as is&rdquo; without any warranty, express or implied.
        </p>

        <h2 className="text-lg font-semibold">7. Affiliate Disclosure</h2>
        <p>
          Some pages on The Ba Zi may contain affiliate links. If you purchase through these links,
          we may earn a small commission at no additional cost to you. See our full
          <a href="/affiliate-disclosure" className="text-red-600 hover:underline"> Affiliate Disclosure</a> for details.
        </p>

        <h2 className="text-lg font-semibold">8. Third-Party Links</h2>
        <p>
          Our site may contain links to third-party websites or services. We are not responsible for
          the content, privacy policies, or practices of any third-party sites.
        </p>

        <h2 className="text-lg font-semibold">9. Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. Changes will be effective immediately
          upon posting. Continued use of the site after changes constitutes acceptance of the new terms.
        </p>

        <h2 className="text-lg font-semibold">10. Contact</h2>
        <p>
          For questions about these terms, please contact us at: <strong>legal@thebazi.com</strong>
        </p>
      </div>
    </div>
  );
}
